//! The canonical path-keyed file catalog: the one record of what a version
//! holds, what it serves, and who may see it.
//!
//! A path names its **source** object (the byte the publisher uploaded, before
//! any transform rewrote it), its **served** object (the immutable byte this
//! version answers with, `null` when the path is held privately), its
//! visibility, and — per channel — the variant object that channel serves
//! instead of the base. It replaces the overlapping `files`, `manifest`,
//! `publicFiles`, `originalShas` and `templateVariants` projections, which
//! finalize keeps emitting until each of their readers has rehomed.
//!
//! Two rules the shape must keep:
//!
//! * Content hashes stay plain JSON strings — never split, prefixed, or
//!   wrapped. The blob collector sweeps every 64-hex string it finds in a
//!   version's declarations down to 12 nesting levels
//!   (`runtime/engine/admin/tier.php`) and is deliberately shape-agnostic so a
//!   schema change cannot make it delete live bytes.
//! * The catalog rides INSIDE `metadata.json`, under one `catalog` key — never
//!   as a sibling document. The blob collector decides liveness by sweeping
//!   that ONE document; a hash in a sibling file would be invisible to it and
//!   its blob collected while the catalog still names it. Riding inside the
//!   swept document is what lets the five legacy maps drop without teaching
//!   the collector anything.

use serde::{Deserialize, Serialize};
use serde_json::{Map, Value};
use std::collections::{BTreeMap, BTreeSet};
use std::fs;
use std::path::Path;

use crate::finalize::{
    invalid, invalid_error, mime_for_path, rewrite_json_compact, FileMeta, FinalizeError, Result,
};
use crate::hash::stable_json_sha256;
use crate::protocol::CACHE_CLASS_IMMUTABLE;
use crate::responses::compiled_cache_class;
use crate::serving_paths::is_public_serving_path;
use crate::storage::blob_path;

pub const FILE_CATALOG_FORMAT: &str = "spacefast.runtime.file-catalog.v1";

/// The key the catalog is published under inside a version's `metadata.json`.
/// Kept in step with `STATTIC_RUNTIME_VERSION_CATALOG_KEY` in
/// `runtime/engine/shared/storage.php`, which is the only reader.
pub const VERSION_CATALOG_METADATA_KEY: &str = "catalog";

/// The key the finalize delta is recorded under inside `metadata.json`, so a
/// replayed finalize answers with the delta it answered the first time instead
/// of recomputing one against a live version that has since moved.
pub const CATALOG_DELTA_METADATA_KEY: &str = "catalogDelta";

/// The key the catalog's two digests are recorded under inside `metadata.json`.
/// They are derived from the catalog, but the derivation is Rust's
/// (`stable_json_sha256`), so recording them is what lets the PHP layer answer a
/// replayed finalize without re-running the finalizer.
pub const CATALOG_DIGESTS_METADATA_KEY: &str = "catalogDigests";

/// The most scoped request paths a purge is worth expressing as a list. Beyond
/// it the caller purges host-wide, because enumerating more URLs than this
/// costs more than dropping the whole host cache. Kept in step with
/// `RUNTIME_CHANGED_PATHS_MAX` in `packages/common/src/contracts/runtime-api.ts`
/// until that constant's last reader is gone.
pub const CHANGED_PATHS_MAX: usize = 900;

/// One immutable object, as the catalog names it.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ObjectIdentity {
    pub sha256: String,
    pub size: u64,
    pub content_type: String,
}

/// One committed path.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CatalogPath {
    /// The uploaded (pre-substitution) object. Always present: every committed
    /// path has bytes in the CAS, including one the pipeline generated — for
    /// which the generated byte IS the source, there being no upload behind it.
    pub source: ObjectIdentity,
    /// The object this version serves at this path, or `null` when the path is
    /// a private compile input that answers nothing.
    pub served: Option<ObjectIdentity>,
    pub public: bool,
}

/// The canonical catalog for one version.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct FileCatalog {
    pub format: String,
    pub space_id: String,
    pub version_id: String,
    pub paths: BTreeMap<String, CatalogPath>,
    /// Runtime route name → the paths whose served object differs from the base
    /// for that channel. Sparse on purpose: a channel serves the base object for
    /// every path it does not override, so recording the whole file set per
    /// channel would repeat the catalog once per channel.
    #[serde(default)]
    pub variants: BTreeMap<String, BTreeMap<String, ObjectIdentity>>,
    /// Folds everything outside the file set that decides what a URL answers:
    /// compiled redirects, compiled headers, the resolved serving config, and
    /// the control plane's own serving state. Two versions that disagree here
    /// cannot have their purge scoped to changed files.
    pub serving_digest: String,
    /// Paths whose bytes are produced by variable substitution. A publish that
    /// changes only a variable's value leaves every source hash alone, so these
    /// paths are always treated as changed.
    #[serde(default)]
    pub template_paths: Vec<String>,
    /// When the version this catalog describes was finalized. Empty for a
    /// catalog recovered by the one-time migration from a version whose
    /// metadata recorded none.
    #[serde(default)]
    pub generated_at: String,
    /// Digest over every input the content pipeline's decoration pass reads
    /// besides the file bytes themselves. A later finalize may adopt this
    /// version's served identity for a source-unchanged file ONLY when its own
    /// digest matches; absent on catalogs written before the incremental path
    /// existed, which disables adoption against them.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub pipeline_context_digest: Option<String>,
}

/// The two scalars the control plane keeps on the version row instead of a file
/// list. Neither folds in the version id or the publish time, so they are
/// comparable ACROSS versions — which is the whole point: noop detection is a
/// scalar comparison, not a manifest replay.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CatalogDigests {
    /// Over path → source sha. Two publishes of the same uploaded files agree
    /// here even when transforms, variables, or serving config differ.
    pub source: String,
    /// Over path → served sha (absent for a private path) plus the per-channel
    /// overrides. Two versions agree here only when they answer identically.
    pub served: String,
}

/// The shape the served digest is taken over: path → served sha (absent for a
/// private path) plus the per-channel overrides.
#[derive(Serialize)]
struct ServedDigestInput<'a> {
    paths: BTreeMap<&'a str, Option<&'a str>>,
    variants: BTreeMap<&'a str, BTreeMap<&'a str, &'a str>>,
}

impl FileCatalog {
    pub fn digests(&self) -> CatalogDigests {
        CatalogDigests {
            source: stable_json_sha256(
                &self
                    .paths
                    .iter()
                    .map(|(path, entry)| (path.as_str(), entry.source.sha256.as_str()))
                    .collect::<BTreeMap<_, _>>(),
            ),
            served: stable_json_sha256(&ServedDigestInput {
                paths: self
                    .paths
                    .iter()
                    .map(|(path, entry)| {
                        (
                            path.as_str(),
                            entry.served.as_ref().map(|served| served.sha256.as_str()),
                        )
                    })
                    .collect(),
                variants: self
                    .variants
                    .iter()
                    .map(|(channel, overrides)| {
                        (
                            channel.as_str(),
                            overrides
                                .iter()
                                .map(|(path, object)| (path.as_str(), object.sha256.as_str()))
                                .collect(),
                        )
                    })
                    .collect(),
            }),
        }
    }
}

/// What one finalize changed relative to the version it supersedes.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CatalogDelta {
    pub added: usize,
    pub changed: usize,
    pub removed: usize,
    /// The request paths whose cached responses this publish invalidates.
    /// `null` means the purge cannot be scoped and the caller must drop the
    /// whole host cache.
    pub changed_paths: Option<Vec<String>>,
}

/// The serving behaviors that decide whether a scoped purge can be trusted.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct DeltaServing {
    /// The index document name, or `None` for `index: false`.
    pub index: Option<String>,
    pub listing: bool,
    pub viewer: bool,
}

impl DeltaServing {
    /// Reads the resolved serving config finalize compiled.
    pub fn from_serving_config(config: &Map<String, Value>) -> Self {
        Self {
            index: match config.get("index") {
                Some(Value::String(index)) => Some(index.clone()),
                Some(Value::Bool(false)) => None,
                _ => Some("index.html".into()),
            },
            listing: config
                .get("listing")
                .and_then(Value::as_bool)
                .unwrap_or(false),
            viewer: config
                .get("viewer")
                .and_then(Value::as_bool)
                .unwrap_or(false),
        }
    }
}

/// The paths this version declares immutable, so a purge can leave them alone.
///
/// Two layers, both deterministic: the framework build directories the crate
/// already pins a year-long `Cache-Control` on, and whatever the publisher's
/// own `_headers` rules declare immutable. Purge planning reads the same
/// declaration that sets the header, so invalidation cannot disagree with
/// caching.
#[derive(Debug, Default)]
pub struct ImmutablePaths {
    /// `(matcher, declares immutable)` in compiled order; later rules win.
    rules: Vec<(HeaderPathMatcher, bool)>,
}

#[derive(Debug)]
enum HeaderPathMatcher {
    Exact(String),
    Pattern(regex::Regex),
    /// A matcher the compiler cannot evaluate. It matches nothing here: an
    /// unreadable rule must never be the reason a changed URL is left in the
    /// edge cache.
    Opaque,
}

impl ImmutablePaths {
    /// Builds the policy from the compiled header buckets this version
    /// publishes. Host-scoped rules are skipped: a declaration that holds for
    /// one hostname says nothing about the others a space serves, and the purge
    /// set is not per-host.
    pub fn from_header_rules(exact: &Map<String, Value>, pattern: &[Value]) -> Self {
        let mut ordered: Vec<&Value> = exact
            .values()
            .flat_map(|bucket| bucket.as_array().into_iter().flatten())
            .chain(pattern.iter())
            .filter(|rule| rule.get("host").is_none() && rule.get("hostRegex").is_none())
            .collect();
        ordered.sort_by_key(|rule| {
            rule.get("order")
                .and_then(Value::as_i64)
                .unwrap_or(i64::MAX)
        });
        let rules = ordered
            .into_iter()
            .filter_map(|rule| {
                let declares = rule
                    .get("operations")
                    .and_then(Value::as_array)
                    .into_iter()
                    .flatten()
                    .filter(|operation| {
                        operation
                            .get("name")
                            .and_then(Value::as_str)
                            .is_some_and(|name| name.eq_ignore_ascii_case("cache-control"))
                    })
                    .map(declares_immutable)
                    .next_back()?;
                Some((header_path_matcher(rule), declares))
            })
            .collect();
        Self { rules }
    }

    /// Whether this committed path's response is declared immutable — the
    /// verdict [`compiled_cache_class`] serves by, with the one asymmetry the
    /// rules give this side: it knows a matching rule's VALUE (immutable or
    /// not), where the compiler only knows a rule exists.
    pub fn contains(&self, path: &str) -> bool {
        if !self.rules.is_empty() {
            let request_path = format!("/{path}");
            let mut rule_verdict = None;
            for (matcher, declares) in &self.rules {
                if matcher.matches(&request_path) {
                    rule_verdict = Some(*declares);
                }
            }
            if let Some(declares) = rule_verdict {
                return declares;
            }
        }
        compiled_cache_class(path, path, None, false) == Some(CACHE_CLASS_IMMUTABLE)
    }
}

fn declares_immutable(operation: &Value) -> bool {
    operation.get("kind").and_then(Value::as_str) == Some("set")
        && operation
            .get("value")
            .and_then(Value::as_str)
            .is_some_and(|value| {
                value
                    .split(',')
                    .any(|directive| directive.trim().eq_ignore_ascii_case("immutable"))
            })
}

fn header_path_matcher(rule: &Value) -> HeaderPathMatcher {
    if let Some(regex) = rule
        .get("regex")
        .and_then(Value::as_str)
        .filter(|regex| !regex.is_empty())
    {
        return regex::Regex::new(regex)
            .map_or(HeaderPathMatcher::Opaque, HeaderPathMatcher::Pattern);
    }
    rule.get("path")
        .and_then(Value::as_str)
        .map_or(HeaderPathMatcher::Opaque, |path| {
            HeaderPathMatcher::Exact(path.to_string())
        })
}

impl HeaderPathMatcher {
    fn matches(&self, request_path: &str) -> bool {
        match self {
            Self::Exact(path) => path == request_path,
            Self::Pattern(regex) => regex.is_match(request_path),
            Self::Opaque => false,
        }
    }
}

/// Everything finalize knows about one version's files, as the catalog builder
/// needs it.
pub struct CatalogInput<'a> {
    pub space_id: &'a str,
    pub version_id: &'a str,
    /// The served file map, after the content pipeline and template overwrites.
    pub files: &'a BTreeMap<String, FileMeta>,
    /// Path → the uploaded object a transform replaced, for the paths that were
    /// rewritten. A path absent here was never rewritten, so it serves what was
    /// uploaded and source equals served.
    pub originals: &'a BTreeMap<String, ObjectIdentity>,
    /// The paths this version serves publicly, as [`crate::artifacts::public_files`]
    /// resolved them. That function is the ONE visibility implementation; the
    /// catalog records its answer so nothing downstream — PHP, TypeScript, or a
    /// second Rust call site — has to reach the same conclusion independently.
    pub public: &'a BTreeSet<String>,
    /// Runtime route name → that channel's complete file map, as the variant
    /// response tables were compiled from.
    pub variants: &'a BTreeMap<String, BTreeMap<String, FileMeta>>,
    pub serving_digest: String,
    pub template_paths: Vec<String>,
    pub generated_at: &'a str,
    /// See [`FileCatalog::pipeline_context_digest`].
    pub pipeline_context_digest: Option<String>,
}

/// Builds the canonical catalog. Visibility is decided exactly once, here.
pub fn build_catalog(input: &CatalogInput<'_>) -> FileCatalog {
    let mut paths = BTreeMap::new();
    for (path, meta) in input.files {
        let public = input.public.contains(path);
        let served = identity_of(meta);
        let source = input
            .originals
            .get(path)
            .cloned()
            .unwrap_or_else(|| served.clone());
        paths.insert(
            path.clone(),
            CatalogPath {
                source,
                served: public.then_some(served),
                public,
            },
        );
    }

    let mut variants = BTreeMap::new();
    for (route_name, route_files) in input.variants {
        let overrides: BTreeMap<String, ObjectIdentity> = route_files
            .iter()
            .filter(|(path, meta)| {
                input
                    .files
                    .get(*path)
                    .is_none_or(|base| base.sha256 != meta.sha256)
            })
            .map(|(path, meta)| (path.clone(), identity_of(meta)))
            .collect();
        variants.insert(route_name.clone(), overrides);
    }

    FileCatalog {
        format: FILE_CATALOG_FORMAT.into(),
        space_id: input.space_id.into(),
        version_id: input.version_id.into(),
        paths,
        variants,
        serving_digest: input.serving_digest.clone(),
        template_paths: input.template_paths.clone(),
        generated_at: input.generated_at.into(),
        pipeline_context_digest: input.pipeline_context_digest.clone(),
    }
}

/// The image a space card shows for this version.
///
/// It must be a path this version actually SERVES publicly, because the card
/// addresses it on the version's own public URL. First by path order, which is
/// the order every catalog reader sees: the choice has to be stable across a
/// replay, and "first image" is what the space card has always shown.
pub fn preview_image_path(catalog: &FileCatalog) -> Option<&str> {
    catalog
        .paths
        .iter()
        .find(|(path, entry)| {
            entry.public
                && entry
                    .served
                    .as_ref()
                    .is_some_and(|served| is_preview_image(path, &served.content_type))
        })
        .map(|(path, _)| path.as_str())
}

fn is_preview_image(path: &str, content_type: &str) -> bool {
    if content_type.to_ascii_lowercase().starts_with("image/") {
        return true;
    }
    let lowered = path.to_ascii_lowercase();
    [".avif", ".gif", ".jpg", ".jpeg", ".png", ".svg", ".webp"]
        .iter()
        .any(|extension| lowered.ends_with(extension))
}

fn identity_of(meta: &FileMeta) -> ObjectIdentity {
    ObjectIdentity {
        sha256: meta.sha256.clone(),
        size: meta.size,
        content_type: meta.mime.clone(),
    }
}

/// Diffs two local catalogs.
///
/// Counts are over SOURCE identity — what the publisher changed, which is what
/// a changelog reports. The scoped purge set is built from the same walk, plus
/// the template paths of both sides: a publish that only changes a variable's
/// value leaves every source hash alone while changing the bytes at those URLs.
pub fn catalog_delta(
    previous: &FileCatalog,
    next: &FileCatalog,
    serving: &DeltaServing,
    immutable: &ImmutablePaths,
) -> CatalogDelta {
    let mut added = 0usize;
    let mut changed_count = 0usize;
    let mut removed = 0usize;
    let mut changed: BTreeSet<String> = next
        .template_paths
        .iter()
        .chain(previous.template_paths.iter())
        .cloned()
        .collect();
    let mut paths_added_or_removed = false;

    for (path, entry) in &next.paths {
        match previous.paths.get(path) {
            None => {
                added += 1;
                // An added immutable path is a URL no cache has ever seen —
                // content-addressed output changes its filename, so the new name
                // was never requested, let alone stored. Purging it is a
                // guaranteed no-op, and emitting it anyway is what pushes a
                // bundler's release past CHANGED_PATHS_MAX into a host-wide purge
                // that evicts the UNCHANGED chunks still serving from the edge.
                paths_added_or_removed = true;
                if !immutable.contains(path) {
                    changed.insert(path.clone());
                }
            }
            Some(before) => {
                if before.source.sha256 != entry.source.sha256 {
                    changed_count += 1;
                    // Same URL, different bytes. An immutable declaration is the
                    // publisher's promise that this cannot happen; since it did,
                    // honor the bytes and purge.
                    changed.insert(path.clone());
                }
            }
        }
    }
    for path in previous.paths.keys() {
        if next.paths.contains_key(path) {
            continue;
        }
        removed += 1;
        paths_added_or_removed = true;
        // Nothing references a content-addressed name after it leaves the
        // catalog, and letting the old bytes age out is what keeps a page
        // already open in a browser able to finish loading its chunks.
        if !immutable.contains(path) {
            changed.insert(path.clone());
        }
    }

    let counts = |changed_paths| CatalogDelta {
        added,
        changed: changed_count,
        removed,
        changed_paths,
    };

    // Listing and viewer output enumerates the file set, so any add or removal
    // rewrites documents at URLs no file path names.
    if (serving.listing || serving.viewer) && paths_added_or_removed {
        return counts(None);
    }

    let mut request_paths = BTreeSet::new();
    for path in &changed {
        request_paths.insert(format!("/{path}"));
        // The runtime also serves a flat `<name>.html` file at its extensionless
        // URL, resolved from the file map rather than the index setting, so a
        // changed `.html` file must purge that alias too.
        if let Some(clean) = path.strip_suffix(".html") {
            request_paths.insert(format!("/{clean}"));
        }
        let Some(index) = &serving.index else {
            continue;
        };
        if path == index {
            request_paths.insert("/".into());
        } else if let Some(directory) = path.strip_suffix(&format!("/{index}")) {
            request_paths.insert(format!("/{directory}"));
            request_paths.insert(format!("/{directory}/"));
        }
    }
    if request_paths.len() > CHANGED_PATHS_MAX {
        return counts(None);
    }
    counts(Some(request_paths.into_iter().collect()))
}

/// Reads a published version's catalog.
///
/// `Ok(None)` means the version predates the catalog and has not been migrated
/// yet; a present-but-unreadable catalog is an error, never a silent miss —
/// reconstructing one from a second projection is the split brain this replaced.
pub fn read_version_catalog(version_root: &Path) -> Result<Option<FileCatalog>> {
    let path = version_root.join("metadata.json");
    let Ok(bytes) = fs::read(&path) else {
        return Ok(None);
    };
    let metadata: Value = serde_json::from_slice(&bytes).map_err(|source| FinalizeError::Json {
        path: path.clone(),
        source,
    })?;
    let Some(embedded) = metadata.get(VERSION_CATALOG_METADATA_KEY) else {
        return Ok(None);
    };
    let catalog: FileCatalog = serde_json::from_value(embedded.clone()).map_err(|_| {
        invalid_error(
            "runtime_file_catalog_invalid",
            format!("{} does not embed a readable catalog.", path.display()),
        )
    })?;
    if catalog.format != FILE_CATALOG_FORMAT {
        return invalid(
            "runtime_file_catalog_invalid",
            format!("{} embeds an unknown catalog format.", path.display()),
        );
    }
    Ok(Some(catalog))
}

/// Publishes the catalog into the version's `metadata.json` — the one document
/// the blob collector sweeps, which is why it must never live anywhere else.
///
/// The rewrite is compact and never creates the version directory: this document
/// is read back before it is written, so a missing parent means the version was
/// deleted underneath the caller.
pub fn write_version_catalog(version_root: &Path, catalog: &FileCatalog) -> Result<()> {
    let path = version_root.join("metadata.json");
    let bytes = fs::read(&path).map_err(|source| FinalizeError::Io {
        path: path.clone(),
        source,
    })?;
    let mut metadata: Value =
        serde_json::from_slice(&bytes).map_err(|source| FinalizeError::Json {
            path: path.clone(),
            source,
        })?;
    let Some(fields) = metadata.as_object_mut() else {
        return invalid(
            "runtime_file_catalog_invalid",
            format!("{} is not a metadata object.", path.display()),
        );
    };
    fields.insert(
        VERSION_CATALOG_METADATA_KEY.to_string(),
        serde_json::to_value(catalog).map_err(|source| FinalizeError::Json {
            path: path.clone(),
            source,
        })?,
    );
    rewrite_json_compact(&path, &metadata)
}

/// Projects an already-finalized `metadata.json` onto the canonical catalog.
///
/// This is the one-time migration for versions finalized before the catalog
/// existed. They cannot be refinalized — finalize deletes its own staging trees
/// — so every field is recovered from what the version recorded:
///
/// * `files` → served identity;
/// * `originalShas` → source sha, with the size re-derived from the CAS object
///   and the content type taken from the served entry for the same path (same
///   path, same declared type — strictly better than guessing from the
///   extension, and it keeps a transformed catalog comparable with a freshly
///   finalized one);
/// * visibility recomputed from the serving-path policy and then intersected
///   with the recorded `publicFiles`. Recomputation alone is unsound: the
///   content pipeline's private set was never recorded, so a path the pipeline
///   held back would come back public. Intersecting fails closed.
/// * `templateVariants` → the sparse per-channel overrides.
///
/// The serving digest is recomputed from what the version recorded, WITHOUT the
/// control plane's serving state, so a transformed catalog never compares equal
/// to a freshly finalized one. The first publish after the migration therefore
/// purges host-wide, which is the safe direction and happens once.
pub fn catalog_from_metadata(metadata: &Value, blobs: &Path) -> Result<FileCatalog> {
    let Some(metadata) = metadata.as_object() else {
        return invalid(
            "runtime_file_catalog_invalid",
            "Version metadata is not an object.",
        );
    };
    let space_id = required_str(metadata, "spaceId")?;
    let version_id = required_str(metadata, "versionId")?;
    let files = metadata
        .get("files")
        .and_then(Value::as_object)
        .ok_or_else(|| {
            invalid_error(
                "runtime_file_catalog_invalid",
                format!("Version {version_id} records no file map."),
            )
        })?;
    let recorded_public: Option<BTreeSet<&str>> = metadata
        .get("publicFiles")
        .and_then(Value::as_array)
        .map(|paths| paths.iter().filter_map(Value::as_str).collect());
    let originals = metadata
        .get("originalShas")
        .and_then(Value::as_object)
        .cloned()
        .unwrap_or_default();
    let committed: BTreeSet<&str> = files.keys().map(String::as_str).collect();

    let mut paths = BTreeMap::new();
    for (path, entry) in files {
        let served = metadata_identity(path, entry, version_id)?;
        let public = is_public_serving_path(path, |source| committed.contains(source))
            && recorded_public
                .as_ref()
                .is_none_or(|recorded| recorded.contains(path.as_str()));
        let source = match originals.get(path).and_then(Value::as_str) {
            Some(sha) => ObjectIdentity {
                size: cas_object_size(blobs, sha).ok_or_else(|| {
                    invalid_error(
                        "runtime_file_catalog_invalid",
                        format!(
                            "Version {version_id} names an uploaded object for {path} that is not in the CAS."
                        ),
                    )
                })?,
                content_type: served.content_type.clone(),
                sha256: sha.to_string(),
            },
            None => served.clone(),
        };
        paths.insert(
            path.clone(),
            CatalogPath {
                source,
                served: public.then(|| served.clone()),
                public,
            },
        );
    }

    let mut variants = BTreeMap::new();
    for (route_name, route_files) in metadata
        .get("templateVariants")
        .and_then(Value::as_object)
        .cloned()
        .unwrap_or_default()
    {
        let Some(route_files) = route_files.as_object() else {
            return invalid(
                "runtime_file_catalog_invalid",
                format!("Version {version_id} records an unreadable {route_name} variant."),
            );
        };
        let mut overrides = BTreeMap::new();
        for (path, entry) in route_files {
            let identity = metadata_identity(path, entry, version_id)?;
            let base = files
                .get(path)
                .and_then(|base| base.get("sha256"))
                .and_then(Value::as_str);
            if base != Some(identity.sha256.as_str()) {
                overrides.insert(path.clone(), identity);
            }
        }
        variants.insert(route_name.clone(), overrides);
    }

    Ok(FileCatalog {
        format: FILE_CATALOG_FORMAT.into(),
        space_id: space_id.into(),
        version_id: version_id.into(),
        paths,
        variants,
        serving_digest: serving_digest(
            metadata.get("redirects").unwrap_or(&Value::Null),
            metadata.get("headers").unwrap_or(&Value::Null),
            metadata.get("servingConfig").unwrap_or(&Value::Null),
            None,
        ),
        template_paths: Vec::new(),
        generated_at: metadata
            .get("generatedAt")
            .and_then(Value::as_str)
            .unwrap_or_default()
            .into(),
        // A recovered catalog never carries the digest: the decoration inputs
        // were not recorded, so adoption against it must stay disabled.
        pipeline_context_digest: None,
    })
}

/// The digest two versions must share before a purge may be scoped to files.
pub fn serving_digest(
    redirects: &Value,
    headers: &Value,
    serving_config: &Value,
    control_plane_state: Option<&Value>,
) -> String {
    stable_json_sha256(&serde_json::json!({
        "redirects": redirects,
        "headers": headers,
        "serving": serving_config,
        "state": control_plane_state.cloned().unwrap_or(Value::Null),
    }))
}

fn required_str<'a>(metadata: &'a Map<String, Value>, key: &str) -> Result<&'a str> {
    metadata
        .get(key)
        .and_then(Value::as_str)
        .filter(|value| !value.is_empty())
        .ok_or_else(|| {
            invalid_error(
                "runtime_file_catalog_invalid",
                format!("Version metadata records no {key}."),
            )
        })
}

fn metadata_identity(path: &str, entry: &Value, version_id: &str) -> Result<ObjectIdentity> {
    let invalid_entry = || {
        invalid_error(
            "runtime_file_catalog_invalid",
            format!("Version {version_id} records an unreadable entry for {path}."),
        )
    };
    let sha256 = entry
        .get("sha256")
        .and_then(Value::as_str)
        .filter(|sha| is_content_hash(sha))
        .ok_or_else(invalid_entry)?
        .to_string();
    let size = entry
        .get("size")
        .and_then(Value::as_u64)
        .ok_or_else(invalid_entry)?;
    let content_type = entry
        .get("mime")
        .and_then(Value::as_str)
        .filter(|mime| !mime.is_empty())
        .map_or_else(|| mime_for_path(path, None), str::to_string);
    Ok(ObjectIdentity {
        sha256,
        size,
        content_type,
    })
}

fn is_content_hash(value: &str) -> bool {
    value.len() == 64 && value.bytes().all(|byte| byte.is_ascii_hexdigit())
}

/// The suffix the storage tier appends to a blob path to mark its bytes as
/// demoted to S3. Kept in step with `STATTIC_BLOB_DEMOTE_MARK_SUFFIX` in
/// `runtime/engine/shared/storage.php`.
const BLOB_DEMOTE_MARK_SUFFIX: &str = ".demote";

/// The size of a source object, and by returning `Some` the statement that the
/// CAS still holds it.
///
/// A local body is not what makes a blob a live CAS member: the tier deletes
/// demoted bodies and leaves the sidecar behind as the evidence the bytes are in
/// S3 (`runtime/engine/admin/tier.php`), so a perfectly live version whose bytes
/// were tiered out has to project as cleanly as one whose bytes are on disk.
fn cas_object_size(blobs: &Path, sha: &str) -> Option<u64> {
    if !is_content_hash(sha) {
        return None;
    }
    let blob = blob_path(blobs, sha);
    match fs::metadata(&blob) {
        Ok(metadata) if metadata.is_file() => Some(metadata.len()),
        _ => demoted_object_size(&blob),
    }
}

/// The size a demote sidecar records, or `None` when there is no sidecar or it
/// states no size we can trust. Failing closed here is what keeps the migration
/// from writing a catalog whose source sizes are invented.
fn demoted_object_size(blob: &Path) -> Option<u64> {
    let mut mark = blob.file_name()?.to_os_string();
    mark.push(BLOB_DEMOTE_MARK_SUFFIX);
    let recorded: Value =
        serde_json::from_slice(&fs::read(blob.with_file_name(mark)).ok()?).ok()?;
    recorded.get("bytes")?.as_u64()
}

/// What one version's migration did.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TransformedVersion {
    pub space_id: String,
    pub version_id: String,
    pub outcome: TransformOutcome,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum TransformOutcome {
    /// A catalog was written into this version's `metadata.json`.
    Transformed,
    /// The version already had a readable catalog.
    AlreadyPresent,
    /// The version could not be projected. Coverage is not exact; the release
    /// gate must stop here rather than let a catalog-less version reach a
    /// runtime that cannot answer for it.
    Failed,
}

/// The migration report the release gate reads.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TransformReport {
    pub format: String,
    pub versions: Vec<TransformedVersion>,
    pub transformed: usize,
    pub already_present: usize,
    pub failed: usize,
}

pub const TRANSFORM_REPORT_FORMAT: &str = "spacefast.runtime.file-catalog.transform.v1";

/// Writes the catalog into one already-finalized version, in place.
pub fn transform_version(version_root: &Path, blobs: &Path) -> Result<TransformOutcome> {
    if read_version_catalog(version_root)?.is_some() {
        return Ok(TransformOutcome::AlreadyPresent);
    }
    let path = version_root.join("metadata.json");
    let bytes = fs::read(&path).map_err(|source| FinalizeError::Io {
        path: path.clone(),
        source,
    })?;
    let metadata: Value = serde_json::from_slice(&bytes).map_err(|source| FinalizeError::Json {
        path: path.clone(),
        source,
    })?;
    commit_transformed_catalog(version_root, &catalog_from_metadata(&metadata, blobs)?)?;
    Ok(TransformOutcome::Transformed)
}

/// Writes a projected catalog back into a version that must still be there.
///
/// The sweep runs inside the publish freeze but not inside the per-space lock,
/// so a delete can take the version between the read that produced this catalog
/// and this write. Neither guard is enough alone: the check names the race in
/// the report the release gate reads, and the in-place write closes the window
/// that stays open after it — without it the atomic writer's `create_dir_all`
/// would rebuild the version directory and leave a zombie the runtime serves.
fn commit_transformed_catalog(version_root: &Path, catalog: &FileCatalog) -> Result<()> {
    if !version_root.is_dir() {
        return invalid(
            "runtime_version_deleted",
            format!(
                "Version {} was deleted while its catalog was being projected.",
                catalog.version_id
            ),
        );
    }
    write_version_catalog(version_root, catalog)
}

/// Sweeps every retained version under a private storage root.
///
/// One version's failure does not abort the sweep: the release gate needs the
/// complete coverage picture, not the first problem.
pub fn transform_private_root(private_root: &Path) -> Result<TransformReport> {
    let mut versions = Vec::new();
    for space in read_dir_sorted(&private_root.join("spaces"))? {
        let space_id = file_name(&space);
        if space_id.starts_with('.') {
            continue;
        }
        let blobs = space.join("blobs");
        for version in read_dir_sorted(&space.join("versions"))? {
            let version_id = file_name(&version);
            // Staging and rollback trees carry a leading dot and are not
            // versions anyone can serve.
            if version_id.starts_with('.') || !version.join("metadata.json").is_file() {
                continue;
            }
            let (outcome, reason) = match transform_version(&version, &blobs) {
                Ok(outcome) => (outcome, None),
                Err(error) => (TransformOutcome::Failed, Some(error.to_string())),
            };
            versions.push(TransformedVersion {
                space_id: space_id.clone(),
                version_id,
                outcome,
                reason,
            });
        }
    }
    let count = |wanted: TransformOutcome| {
        versions
            .iter()
            .filter(|version| version.outcome == wanted)
            .count()
    };
    Ok(TransformReport {
        format: TRANSFORM_REPORT_FORMAT.into(),
        transformed: count(TransformOutcome::Transformed),
        already_present: count(TransformOutcome::AlreadyPresent),
        failed: count(TransformOutcome::Failed),
        versions,
    })
}

fn read_dir_sorted(root: &Path) -> Result<Vec<std::path::PathBuf>> {
    if !root.is_dir() {
        return Ok(Vec::new());
    }
    let mut entries = fs::read_dir(root)
        .map_err(|source| FinalizeError::Io {
            path: root.into(),
            source,
        })?
        .filter_map(std::result::Result::ok)
        .filter(|entry| entry.path().is_dir())
        .map(|entry| entry.path())
        .collect::<Vec<_>>();
    entries.sort();
    Ok(entries)
}

fn file_name(path: &Path) -> String {
    path.file_name()
        .map(|name| name.to_string_lossy().into_owned())
        .unwrap_or_default()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::finalize::{file_meta, write_json};
    use serde_json::json;
    use tempfile::tempdir;

    fn files(entries: &[(&str, &[u8])]) -> BTreeMap<String, FileMeta> {
        entries
            .iter()
            .map(|(path, bytes)| ((*path).to_string(), file_meta(path, bytes, None)))
            .collect()
    }

    /// The public set finalize resolved, as the catalog builder takes it.
    fn public_set(files: &BTreeMap<String, FileMeta>) -> BTreeSet<String> {
        crate::artifacts::public_files(files, &BTreeSet::new())
            .into_iter()
            .collect()
    }

    fn catalog_of(
        files: &BTreeMap<String, FileMeta>,
        public: &BTreeSet<String>,
        originals: &BTreeMap<String, ObjectIdentity>,
        variants: &BTreeMap<String, BTreeMap<String, FileMeta>>,
    ) -> FileCatalog {
        build_catalog(&CatalogInput {
            space_id: "spc_1",
            version_id: "ver_1",
            files,
            originals,
            public,
            variants,
            serving_digest: "sha256:serving".into(),
            template_paths: Vec::new(),
            generated_at: "2026-08-11T00:00:00Z",
            pipeline_context_digest: None,
        })
    }

    /// A path held back from serving records no served object at all, so a
    /// `view=served` read of one cannot resolve to bytes. (Which paths ARE held
    /// back is the serving-path policy's own behavior, proven where it lives and
    /// again end to end in the finalize differential.)
    #[test]
    fn a_private_path_records_no_served_object() {
        let files = files(&[("index.html", b"<h1>hi</h1>"), ("sf.jsonc", b"{}")]);
        let catalog = catalog_of(
            &files,
            &BTreeSet::from(["index.html".to_string()]),
            &BTreeMap::new(),
            &BTreeMap::new(),
        );

        assert!(catalog.paths["index.html"].public);
        assert!(!catalog.paths["sf.jsonc"].public);
        assert!(catalog.paths["sf.jsonc"].served.is_none());
        assert!(catalog.paths["sf.jsonc"].source.size > 0);
        assert!(catalog.paths["index.html"].served.is_some());
    }

    /// The digests are comparable ACROSS versions — that is what lets the
    /// version row keep two scalars instead of a file list, and what makes
    /// "nothing new was uploaded" a comparison rather than a manifest replay.
    /// Neither folds in the version id or the publish time, and a transform that
    /// changes what is served leaves `source` alone.
    #[test]
    fn digests_identify_content_not_the_version_that_published_it() {
        let files = files(&[("index.html", b"<h1>hi</h1>")]);
        let public = public_set(&files);
        let plain = build_catalog(&CatalogInput {
            space_id: "spc_1",
            version_id: "ver_1",
            files: &files,
            originals: &BTreeMap::new(),
            public: &public,
            variants: &BTreeMap::new(),
            serving_digest: "sha256:serving-a".into(),
            template_paths: Vec::new(),
            generated_at: "2026-08-11T00:00:00Z",
            pipeline_context_digest: None,
        });
        // The same upload republished later, under a different serving state,
        // with the pipeline rewriting the byte it serves.
        let mut rewritten_files = files.clone();
        rewritten_files.insert(
            "index.html".into(),
            file_meta("index.html", b"<h1>hi</h1><!--injected-->", None),
        );
        let rewritten = build_catalog(&CatalogInput {
            space_id: "spc_1",
            version_id: "ver_2",
            files: &rewritten_files,
            originals: &BTreeMap::from([(
                "index.html".to_string(),
                plain.paths["index.html"].source.clone(),
            )]),
            public: &public,
            variants: &BTreeMap::new(),
            serving_digest: "sha256:serving-b".into(),
            template_paths: Vec::new(),
            generated_at: "2026-08-12T00:00:00Z",
            pipeline_context_digest: None,
        });

        assert_eq!(plain.digests().source, rewritten.digests().source);
        assert_ne!(plain.digests().served, rewritten.digests().served);
    }

    /// Source is the uploaded byte and served is what the version answers with;
    /// a rewritten path records both, and every path records a source even when
    /// nothing rewrote it.
    #[test]
    fn source_and_served_are_separate_identities() {
        let files = files(&[
            ("index.html", b"<h1>rewritten</h1>"),
            ("about.html", b"<p>a</p>"),
        ]);
        let originals = BTreeMap::from([(
            "index.html".to_string(),
            ObjectIdentity {
                sha256: "a".repeat(64),
                size: 9,
                content_type: "text/html; charset=utf-8".into(),
            },
        )]);
        let catalog = catalog_of(&files, &public_set(&files), &originals, &BTreeMap::new());

        let rewritten = &catalog.paths["index.html"];
        assert_eq!(rewritten.source.sha256, "a".repeat(64));
        assert_eq!(rewritten.source.size, 9);
        assert_eq!(
            rewritten.served.as_ref().map(|served| &served.sha256),
            Some(&files["index.html"].sha256)
        );
        let untouched = &catalog.paths["about.html"];
        assert_eq!(
            Some(&untouched.source),
            untouched.served.as_ref(),
            "an unrewritten path serves exactly what was uploaded"
        );
    }

    /// A channel records only what it serves DIFFERENTLY. Recording the whole
    /// file set per channel is what made `templateVariants` a second copy of the
    /// catalog for every channel a space has.
    #[test]
    fn variants_record_only_the_paths_a_channel_overrides() {
        let files = files(&[("index.html", b"base"), ("about.html", b"about")]);
        let mut production = files.clone();
        production.insert(
            "index.html".into(),
            file_meta("index.html", b"production", None),
        );
        let variants = BTreeMap::from([("production".to_string(), production)]);
        let catalog = catalog_of(&files, &public_set(&files), &BTreeMap::new(), &variants);

        assert_eq!(
            catalog.variants["production"].keys().collect::<Vec<_>>(),
            vec!["index.html"]
        );
        assert_eq!(
            catalog.variants["production"]["index.html"].sha256,
            file_meta("index.html", b"production", None).sha256
        );
    }

    fn catalog_for(entries: &[(&str, &[u8])]) -> FileCatalog {
        let files = files(entries);
        catalog_of(
            &files,
            &public_set(&files),
            &BTreeMap::new(),
            &BTreeMap::new(),
        )
    }

    fn delta_between(
        previous: &[(&str, &[u8])],
        next: &[(&str, &[u8])],
        serving: &DeltaServing,
    ) -> CatalogDelta {
        catalog_delta(
            &catalog_for(previous),
            &catalog_for(next),
            serving,
            &ImmutablePaths::default(),
        )
    }

    fn static_serving() -> DeltaServing {
        DeltaServing {
            index: Some("index.html".into()),
            listing: false,
            viewer: false,
        }
    }

    /// The three integers the changelog renders, and the request paths the edge
    /// purge takes: a changed index also invalidates the directory URL it
    /// answers at, and an HTML file its extensionless alias.
    #[test]
    fn delta_counts_adds_changes_and_removals_and_scopes_the_purge() {
        let delta = delta_between(
            &[
                ("index.html", b"one"),
                ("docs/index.html", b"docs"),
                ("gone.css", b"old"),
            ],
            &[
                ("index.html", b"two"),
                ("docs/index.html", b"docs"),
                ("new.css", b"new"),
            ],
            &static_serving(),
        );

        assert_eq!((delta.added, delta.changed, delta.removed), (1, 1, 1));
        assert_eq!(
            delta.changed_paths,
            Some(vec![
                "/".to_string(),
                "/gone.css".into(),
                "/index".into(),
                "/index.html".into(),
                "/new.css".into(),
            ])
        );
    }

    /// Generated listings and viewers enumerate the file set, so an add or a
    /// removal rewrites documents at URLs no file path names — the purge cannot
    /// be scoped. A pure content change still can be.
    #[test]
    fn enumerating_serving_modes_force_a_host_wide_purge_on_membership_changes() {
        let listing = DeltaServing {
            index: Some("index.html".into()),
            listing: true,
            viewer: false,
        };
        let added = delta_between(
            &[("a.html", b"a")],
            &[("a.html", b"a"), ("b.html", b"b")],
            &listing,
        );
        assert_eq!(added.added, 1);
        assert_eq!(added.changed_paths, None);

        let edited = delta_between(&[("a.html", b"a")], &[("a.html", b"b")], &listing);
        assert_eq!((edited.added, edited.changed, edited.removed), (0, 1, 0));
        assert!(edited.changed_paths.is_some());
    }

    /// A content-addressed name is never purged when it appears or disappears:
    /// no cache ever held the new name, and evicting the old one drops chunks a
    /// page still loading needs. It still counts as an add or a removal. The
    /// verdict is [`compiled_cache_class`]'s — this test adds the purge-side
    /// cases: a hashed DOCUMENT still purges, and a rule re-pinning a
    /// guaranteed prefix to mutable purges again.
    #[test]
    fn immutable_assets_count_but_are_not_purged() {
        let previous = catalog_for(&[
            ("_next/static/a.js", b"a"),
            ("assets/old.js", b"old"),
            ("static/chunk-XK2FA9.css", b"old chunk"),
            ("page.ab12cd34.html", b"old page"),
            ("_app/immutable/old.js", b"old pinned"),
        ]);
        let next = catalog_for(&[
            ("_next/static/b.js", b"b"),
            ("assets/new.js", b"new"),
            ("static/chunk-YT4QB7.css", b"new chunk"),
            ("page.cd34ef56.html", b"new page"),
            ("_app/immutable/new.js", b"new pinned"),
        ]);
        let declared = ImmutablePaths::from_header_rules(
            &Map::new(),
            &[
                json!({
                    "regex": "^/assets/.*$",
                    "order": 0,
                    "operations": [
                        {"kind": "set", "name": "Cache-Control", "value": "public, max-age=31536000, immutable"}
                    ],
                }),
                // The publisher re-pinned a guaranteed-immutable prefix to a
                // revalidating policy; the serve path honors the rule, so the
                // purge must too.
                json!({
                    "regex": "^/_app/immutable/.*$",
                    "order": 1,
                    "operations": [
                        {"kind": "set", "name": "Cache-Control", "value": "public, max-age=0, must-revalidate"}
                    ],
                }),
            ],
        );

        let delta = catalog_delta(&previous, &next, &static_serving(), &declared);
        assert_eq!((delta.added, delta.changed, delta.removed), (5, 0, 5));
        // The hashed *document* still purges (with its extensionless alias):
        // its URL serves the html class, never the immutable one.
        assert_eq!(
            delta.changed_paths,
            Some(vec![
                "/_app/immutable/new.js".to_string(),
                "/_app/immutable/old.js".into(),
                "/page.ab12cd34".into(),
                "/page.ab12cd34.html".into(),
                "/page.cd34ef56".into(),
                "/page.cd34ef56.html".into(),
            ])
        );
    }

    /// Substitution rewrites bytes without touching a source hash, so a publish
    /// that only changes a variable's value must still purge those URLs — from
    /// either side of the diff, since the path may have stopped being a
    /// template.
    #[test]
    fn template_paths_purge_from_both_sides() {
        let mut previous = catalog_for(&[("index.html", b"x"), ("legacy.html", b"y")]);
        previous.template_paths = vec!["legacy.html".into()];
        let mut next = previous.clone();
        next.template_paths = vec!["index.html".into()];

        let delta = catalog_delta(
            &previous,
            &next,
            &static_serving(),
            &ImmutablePaths::default(),
        );
        assert_eq!((delta.added, delta.changed, delta.removed), (0, 0, 0));
        assert_eq!(
            delta.changed_paths,
            Some(vec![
                "/".to_string(),
                "/index".into(),
                "/index.html".into(),
                "/legacy".into(),
                "/legacy.html".into(),
            ])
        );
    }

    /// Beyond the scoped-purge ceiling the caller drops the whole host cache:
    /// enumerating more URLs than this costs more than the blanket purge.
    #[test]
    fn oversized_purge_sets_fall_back_to_the_whole_host() {
        let previous = catalog_for(&[("keep.txt", b"keep")]);
        let owned: Vec<(String, Vec<u8>)> = (0..=CHANGED_PATHS_MAX)
            .map(|index| (format!("asset-{index}.css"), b"body{}".to_vec()))
            .collect();
        let entries: Vec<(&str, &[u8])> = owned
            .iter()
            .map(|(path, bytes)| (path.as_str(), bytes.as_slice()))
            .collect();
        let next = catalog_for(&entries);

        let delta = catalog_delta(
            &previous,
            &next,
            &static_serving(),
            &ImmutablePaths::default(),
        );
        assert_eq!(delta.added, CHANGED_PATHS_MAX + 1);
        assert_eq!(delta.changed_paths, None);
    }

    /// The migration recovers what a pre-catalog version recorded: served
    /// identity from `files`, source identity from `originalShas` with the size
    /// read back off the CAS object — or, for bytes the tier has demoted to S3,
    /// off the sidecar that outlives the body — visibility fail-closed against
    /// the recorded public set, and the sparse per-channel overrides.
    #[test]
    fn the_migration_projects_a_finalized_version_onto_the_catalog() {
        let temp = tempdir().unwrap();
        let blobs = temp.path().join("blobs");
        let original = b"<h1>uploaded</h1>";
        let original_sha = crate::finalize::sha256(original);
        let blob = blob_path(&blobs, &original_sha);
        fs::create_dir_all(blob.parent().unwrap()).unwrap();
        fs::write(&blob, original).unwrap();
        // `hero.png` is just as live, but the tier moved its bytes to S3 and
        // released the local body. All that is left is the demote sidecar, in
        // the shape `runtime/engine/admin/tier.php` writes it.
        let demoted_sha = "6".repeat(64);
        let demoted = blob_path(&blobs, &demoted_sha);
        fs::create_dir_all(demoted.parent().unwrap()).unwrap();
        fs::write(
            demoted.with_file_name(format!("{demoted_sha}{BLOB_DEMOTE_MARK_SUFFIX}")),
            json!({"reason": "demote", "bytes": 4096, "demoted_at": "2026-08-11T09:14:00+00:00"})
                .to_string(),
        )
        .unwrap();

        let metadata = json!({
            "spaceId": "spc_1",
            "versionId": "ver_1",
            "files": {
                "index.html": {"sha256": "1".repeat(64), "size": 22, "mime": "text/html; charset=utf-8"},
                "sf.jsonc": {"sha256": "2".repeat(64), "size": 2, "mime": "application/json; charset=utf-8"},
                "drafts/notes.md": {"sha256": "3".repeat(64), "size": 7, "mime": "text/markdown; charset=utf-8"},
                "hero.png": {"sha256": "5".repeat(64), "size": 4096, "mime": "image/png"},
            },
            // The content pipeline held `drafts/notes.md` back; nothing in the
            // document says why, which is exactly why the recorded set binds.
            "publicFiles": ["index.html", "hero.png"],
            "originalShas": {"index.html": original_sha, "hero.png": demoted_sha},
            "templateVariants": {
                "production": {
                    "index.html": {"sha256": "4".repeat(64), "size": 30, "mime": "text/html; charset=utf-8"},
                    "sf.jsonc": {"sha256": "2".repeat(64), "size": 2, "mime": "application/json; charset=utf-8"},
                }
            },
        });

        let catalog = catalog_from_metadata(&metadata, &blobs).unwrap();

        assert_eq!(catalog.format, FILE_CATALOG_FORMAT);
        assert_eq!(catalog.paths["index.html"].source.sha256, original_sha);
        assert_eq!(
            catalog.paths["index.html"].source.size,
            original.len() as u64
        );
        assert_eq!(
            catalog.paths["index.html"].served.as_ref().unwrap().sha256,
            "1".repeat(64)
        );
        assert_eq!(
            catalog.paths["hero.png"].source,
            ObjectIdentity {
                sha256: demoted_sha,
                size: 4096,
                content_type: "image/png".into(),
            },
            "a demoted source object is a live CAS member, sized from its sidecar"
        );
        assert!(!catalog.paths["sf.jsonc"].public);
        assert!(!catalog.paths["drafts/notes.md"].public);
        assert!(catalog.paths["drafts/notes.md"].served.is_none());
        assert_eq!(
            catalog.variants["production"].keys().collect::<Vec<_>>(),
            vec!["index.html"],
            "an unchanged path in a channel's file map is not an override"
        );

        // The sweep writes it into the version in place and is idempotent.
        let version = temp.path().join("spaces/spc_1/versions/ver_1");
        fs::create_dir_all(&version).unwrap();
        write_json(&version.join("metadata.json"), &metadata).unwrap();
        fs::rename(&blobs, temp.path().join("spaces/spc_1/blobs")).unwrap();

        let report = transform_private_root(temp.path()).unwrap();
        assert_eq!((report.transformed, report.failed), (1, 0));
        assert_eq!(
            read_version_catalog(&version).unwrap().as_ref(),
            Some(&catalog)
        );
        let again = transform_private_root(temp.path()).unwrap();
        assert_eq!((again.transformed, again.already_present), (0, 1));
    }

    /// A version whose uploaded object left the CAS cannot be projected, and the
    /// sweep reports it instead of writing a catalog that names bytes nobody
    /// has. Coverage has to be exact before the control plane cuts over.
    #[test]
    fn the_migration_reports_a_version_it_cannot_project() {
        let temp = tempdir().unwrap();
        let version = temp.path().join("spaces/spc_1/versions/ver_1");
        fs::create_dir_all(&version).unwrap();
        write_json(
            &version.join("metadata.json"),
            &json!({
                "spaceId": "spc_1",
                "versionId": "ver_1",
                "files": {"index.html": {"sha256": "1".repeat(64), "size": 3, "mime": "text/html"}},
                "publicFiles": ["index.html"],
                "originalShas": {"index.html": "9".repeat(64)},
            }),
        )
        .unwrap();

        let report = transform_private_root(temp.path()).unwrap();
        assert_eq!((report.transformed, report.failed), (0, 1));
        assert_eq!(report.versions[0].outcome, TransformOutcome::Failed);
        assert!(report.versions[0]
            .reason
            .as_deref()
            .unwrap_or_default()
            .contains("runtime_file_catalog_invalid"));
        assert!(read_version_catalog(&version).unwrap().is_none());
    }

    /// A delete can take the version between the read that projects the catalog
    /// and the write that publishes it. The write must refuse: the atomic writer
    /// used to `create_dir_all` its way back into existence, leaving a version
    /// directory nobody owns that the runtime would serve.
    #[test]
    fn the_migration_refuses_a_version_deleted_under_it() {
        let temp = tempdir().unwrap();
        let version = temp.path().join("spaces/spc_1/versions/ver_1");
        fs::create_dir_all(&version).unwrap();
        let metadata = json!({
            "spaceId": "spc_1",
            "versionId": "ver_1",
            "files": {"index.html": {"sha256": "1".repeat(64), "size": 3, "mime": "text/html"}},
            "publicFiles": ["index.html"],
        });
        write_json(&version.join("metadata.json"), &metadata).unwrap();
        let catalog = catalog_from_metadata(&metadata, &temp.path().join("blobs")).unwrap();

        fs::remove_dir_all(&version).unwrap();
        let error = commit_transformed_catalog(&version, &catalog).unwrap_err();

        assert!(
            error.to_string().contains("runtime_version_deleted"),
            "the sweep report has to name the race: {error}"
        );
        assert!(
            !version.exists(),
            "the transform resurrected a dead version"
        );
    }
}
