//! The per-space CAS: staging a version's working tree from it, installing
//! generated bytes into it, and template-file overwrites that preserve the
//! uploaded originals.
//!
//! Bytes only ever enter the CAS under the name their digest addresses, and
//! only where they are hashed as they arrive — at ingest for an upload, here
//! for what the compiler generates. Nothing downstream re-hashes them.

use serde_json::{json, Value};
use sha2::{Digest, Sha256};
use std::collections::{BTreeMap, HashSet};
use std::fs;
use std::fs::File;
use std::io::Read;
use std::path::{Path, PathBuf};

use crate::finalize::{
    create_dir_all, file_meta_from_parts, invalid, invalid_with_details, mime_for_path,
    stamp_content_mtime, validate_id, validate_relative_path, write_generated, FileMeta,
    FinalizeError, Result,
};
use crate::protocol::{TEMPLATE_MAX_BYTES, TEMPLATE_VARIANT_FILE_LIMIT};

/// Remembers the stage directories a commit already created, so staging costs
/// one `mkdir` per directory rather than one per file.
#[derive(Default)]
struct StagedDirs {
    created: HashSet<PathBuf>,
}

impl StagedDirs {
    fn ensure(&mut self, directory: &Path) -> Result<()> {
        if self.created.contains(directory) {
            return Ok(());
        }
        create_dir_all(directory)?;
        self.created.insert(directory.to_path_buf());
        Ok(())
    }
}

/// Stages every path a publish session declares, from the per-space CAS.
///
/// The bytes are already in the CAS under the name their digest addresses, so
/// nothing here re-hashes them. What it proves is the pairing: every manifest
/// path names a sha the session accepted at exactly the declared size, and the
/// CAS object under that name is exactly that long.
pub fn commit_session_files(
    space_id: &str,
    session: &Value,
    private_root: &Path,
    stage_root: &Path,
    files: &mut BTreeMap<String, FileMeta>,
) -> Result<()> {
    let blobs = blob_root(private_root, space_id);
    let files_root = stage_root.join("files");
    let mut directories = StagedDirs::default();

    let retained = session
        .get("retained_files")
        .and_then(Value::as_array)
        .cloned()
        .unwrap_or_default();
    let mut planned = plan_retained_files(
        &blobs,
        &files_root,
        &mut directories,
        &retained,
        session.get("reusable_version_id").and_then(Value::as_str),
    )?;

    let manifest = match session.get("manifest") {
        None | Some(Value::Null) => Vec::new(),
        Some(Value::Array(manifest)) => manifest.clone(),
        Some(_) => {
            return invalid(
                "version_session_invalid",
                "The publish session manifest is not a list of files.",
            );
        }
    };
    let accepted = match session.get("accepted") {
        None | Some(Value::Null) => serde_json::Map::new(),
        Some(Value::Object(accepted)) => accepted.clone(),
        Some(_) => {
            return invalid(
                "version_session_invalid",
                "The publish session accepted set is not an object.",
            );
        }
    };
    planned.extend(plan_accepted_files(
        &blobs,
        &files_root,
        &mut directories,
        &manifest,
        &accepted,
    )?);

    stage_planned_files(&blobs, &files_root, &planned, files)
}

/// One path resolved to the CAS object that carries it, and the length that
/// object turned out to have.
struct PlannedFile<'a> {
    path: String,
    sha: String,
    size: u64,
    entry: &'a Value,
}

/// Above this many paths, spreading the staging across threads buys more than
/// the threads cost. A one-page publish stays on one thread.
const STAGE_PARALLEL_THRESHOLD: usize = 256;

/// The most threads worth pointing at a directory of hardlinks. Measured on a
/// 12k-file version: the win is ~2.9x by four threads and flat after that —
/// this is filesystem metadata latency, not work that more cores can absorb.
const STAGE_MAX_WORKERS: usize = 4;

/// Validates the retained set and resolves each path to its CAS object.
fn plan_retained_files<'a>(
    blobs: &Path,
    files_root: &Path,
    directories: &mut StagedDirs,
    retained: &'a [Value],
    reusable: Option<&str>,
) -> Result<Vec<PlannedFile<'a>>> {
    if retained.is_empty() {
        return Ok(Vec::new());
    }
    let reusable = reusable.ok_or_else(|| FinalizeError::Invalid {
        code: "reusable_version_required",
        message: "Retained files require a reusable version.".into(),
        details: None,
    })?;
    validate_id(reusable, "reusable_version_id")?;
    let mut planned = Vec::with_capacity(retained.len());
    for entry in retained {
        let path = file_entry_path(entry)?;
        let Some(sha) = declared_hash(entry) else {
            return invalid(
                "version_reusable_file_missing",
                format!("A retained file has no content hash: {path}."),
            );
        };
        let Some(size) = cas_object_size(blobs, &sha) else {
            return invalid(
                "version_reusable_file_missing",
                format!("A retained CAS object is missing: {path}."),
            );
        };
        if entry
            .get("size")
            .and_then(Value::as_u64)
            .is_some_and(|declared| declared != size)
        {
            return invalid(
                "version_file_size_mismatch",
                format!("Size mismatch for {path}."),
            );
        }
        directories.ensure(files_root.join(&path).parent().unwrap_or(files_root))?;
        planned.push(PlannedFile {
            path,
            sha,
            size,
            entry,
        });
    }
    Ok(planned)
}

/// Validates the declared manifest against what the session accepted. Every
/// missing path lands in one structured answer, which is what a resuming
/// publisher re-negotiates with `POST /spaces/<s>/blobs/have`.
fn plan_accepted_files<'a>(
    blobs: &Path,
    files_root: &Path,
    directories: &mut StagedDirs,
    manifest: &'a [Value],
    accepted: &serde_json::Map<String, Value>,
) -> Result<Vec<PlannedFile<'a>>> {
    let mut planned = Vec::with_capacity(manifest.len());
    let mut missing_paths = Vec::new();
    for entry in manifest {
        let path = file_entry_path(entry)?;
        let resolved = declared_hash(entry).zip(entry.get("size").and_then(Value::as_u64));
        let Some((sha, declared_size)) = resolved else {
            missing_paths.push(path);
            continue;
        };
        // The session is the authority on what arrived. A sha it never accepted,
        // or accepted at another length, is a path this publish does not have.
        if accepted.get(&sha).and_then(Value::as_u64) != Some(declared_size) {
            missing_paths.push(path);
            continue;
        }
        if cas_object_size(blobs, &sha) != Some(declared_size) {
            missing_paths.push(path);
            continue;
        }
        directories.ensure(files_root.join(&path).parent().unwrap_or(files_root))?;
        planned.push(PlannedFile {
            path,
            sha,
            size: declared_size,
            entry,
        });
    }
    if !missing_paths.is_empty() {
        let missing_count = missing_paths.len();
        let summary = missing_paths.iter().take(20).cloned().collect::<Vec<_>>();
        let suffix = if missing_count > 20 { ", ..." } else { "" };
        return invalid_with_details(
            "version_upload_incomplete",
            format!(
                "Version upload has missing files: {}{suffix}",
                summary.join(", ")
            ),
            json!({
                "missingPaths": missing_paths.into_iter().take(100).collect::<Vec<_>>(),
                "missingCount": missing_count,
            }),
        );
    }
    Ok(planned)
}

/// The length of a CAS object, or `None` when nothing is there under that name.
fn cas_object_size(blobs: &Path, sha: &str) -> Option<u64> {
    let metadata = fs::metadata(blob_path(blobs, sha)).ok()?;
    metadata.is_file().then_some(metadata.len())
}

/// Stages every planned path into the version tree. Validation and directory
/// creation already happened on this thread, so the staging threads share no
/// mutable state.
fn stage_planned_files(
    blobs: &Path,
    files_root: &Path,
    planned: &[PlannedFile<'_>],
    files: &mut BTreeMap<String, FileMeta>,
) -> Result<()> {
    let workers = if planned.len() < STAGE_PARALLEL_THRESHOLD {
        1
    } else {
        std::thread::available_parallelism().map_or(1, |cores| cores.get().min(STAGE_MAX_WORKERS))
    };
    let mut staged: Vec<Option<Result<FileMeta>>> = planned.iter().map(|_| None).collect();
    if workers > 1 {
        let batch = planned.len().div_ceil(workers);
        std::thread::scope(|scope| {
            for (batch_plan, batch_staged) in planned.chunks(batch).zip(staged.chunks_mut(batch)) {
                scope.spawn(move || {
                    for (plan, slot) in batch_plan.iter().zip(batch_staged.iter_mut()) {
                        *slot = Some(stage_planned_file(blobs, files_root, plan));
                    }
                });
            }
        });
    } else {
        for (plan, slot) in planned.iter().zip(staged.iter_mut()) {
            *slot = Some(stage_planned_file(blobs, files_root, plan));
        }
    }
    // Reported in manifest order, so which path a publish blames does not depend
    // on how the staging was spread.
    for (plan, slot) in planned.iter().zip(staged) {
        let meta = slot.expect("every planned file is staged")?;
        files.insert(plan.path.clone(), meta);
    }
    Ok(())
}

/// Stages one planned path: the version's bytes are the CAS object the session
/// names, so the commit is a hardlink and reads nothing.
fn stage_planned_file(blobs: &Path, files_root: &Path, plan: &PlannedFile<'_>) -> Result<FileMeta> {
    let PlannedFile {
        path,
        sha,
        size,
        entry,
    } = plan;
    let declared_mime = entry
        .get("contentType")
        .or_else(|| entry.get("content_type"))
        .and_then(Value::as_str);
    // The leading bytes decide exactly one thing — a gzip sniff — and only for
    // a file nothing else could type.
    let blob = blob_path(blobs, sha);
    let prefix = if mime_for_path(path, declared_mime) == "application/octet-stream" {
        read_prefix(&blob)?
    } else {
        Vec::new()
    };
    link_or_copy(&blob, &files_root.join(path), sha)?;
    Ok(file_meta_from_parts(
        path,
        *size,
        sha.clone(),
        &prefix,
        declared_mime,
    ))
}

/// The manifest-declared content hash, normalized, when the entry carries one
/// in the CAS keyspace's shape. The value that addresses a blob is the value
/// that was validated.
fn declared_hash(entry: &Value) -> Option<String> {
    let sha = entry
        .get("sha256")
        .and_then(Value::as_str)?
        .to_ascii_lowercase();
    (sha.len() == 64 && sha.bytes().all(|byte| byte.is_ascii_hexdigit())).then_some(sha)
}

fn file_entry_path(entry: &Value) -> Result<String> {
    let path = entry
        .get("path")
        .and_then(Value::as_str)
        .ok_or_else(|| FinalizeError::Invalid {
            code: "invalid_file",
            message: "File path is missing.".into(),
            details: None,
        })?;
    validate_relative_path(path)?;
    Ok(path.into())
}

/// Places `blob` at `target` (hardlink, or a copy on a filesystem that cannot
/// link) and stamps the content-derived mtime on it.
///
/// The stamp belongs here because nginx builds `ETag: "<hex mtime>-<hex size>"`
/// off the inode for any file it serves itself, so a placement that forgets it
/// publishes content under a validator derived from the clock. A hardlink would
/// inherit the right value; a copy is a fresh inode and would not.
fn link_or_copy(blob: &Path, target: &Path, hash: &str) -> Result<()> {
    if fs::hard_link(blob, target).is_err() {
        fs::copy(blob, target).map_err(|source| FinalizeError::Io {
            path: target.to_path_buf(),
            source,
        })?;
    }
    stamp_content_mtime(target, hash)
}

/// The first three bytes of a file, for the gzip magic sniff.
fn read_prefix(source: &Path) -> Result<Vec<u8>> {
    let mut file = File::open(source).map_err(|error| FinalizeError::Io {
        path: source.to_path_buf(),
        source: error,
    })?;
    let mut prefix = [0_u8; 3];
    let mut filled = 0;
    while filled < prefix.len() {
        let read = file
            .read(&mut prefix[filled..])
            .map_err(|error| FinalizeError::Io {
                path: source.to_path_buf(),
                source: error,
            })?;
        if read == 0 {
            break;
        }
        filled += read;
    }
    Ok(prefix[..filled].to_vec())
}

/// The per-space CAS root. Derived, never stored.
pub fn blob_root(private_root: &Path, space_id: &str) -> PathBuf {
    private_root.join("spaces").join(space_id).join("blobs")
}

/// The CAS path a content hash addresses.
pub fn blob_path(blob_root: &Path, sha: &str) -> PathBuf {
    blob_root.join(&sha[..2]).join(sha)
}

/// Writes arbitrary generated bytes into the CAS and returns their hash.
/// Content addressing makes the write idempotent: an existing blob of the same
/// name is already the same bytes.
pub fn put_blob(blob_root: &Path, bytes: &[u8]) -> Result<String> {
    let hash = format!("{:x}", Sha256::digest(bytes));
    let blob = blob_path(blob_root, &hash);
    if blob.is_file() {
        return Ok(hash);
    }
    create_dir_all(blob.parent().unwrap_or(blob_root))?;
    let temporary = blob_root.join(format!(".tmp-blob-{hash}"));
    fs::write(&temporary, bytes).map_err(|source| FinalizeError::Io {
        path: temporary.clone(),
        source,
    })?;
    match fs::rename(&temporary, &blob) {
        Ok(()) => {}
        Err(_) if blob.is_file() => {
            let _ = fs::remove_file(&temporary);
        }
        Err(source) => {
            let _ = fs::remove_file(&temporary);
            return Err(FinalizeError::Io { path: blob, source });
        }
    }
    // The garbage collector never deletes a blob newer than the grace time and
    // reads that from the file time, so a publish has to set it. The
    // content-derived stamp is also the ETag nginx will hand out.
    stamp_content_mtime(&blob, &hash)?;
    Ok(hash)
}

/// Installs a staged file's bytes into the CAS under their own hash, for
/// pipeline output that only ever existed in the staging tree.
pub fn install_blob_from(blob_root: &Path, staged: &Path, sha: &str) -> Result<()> {
    let blob = blob_path(blob_root, sha);
    if blob.is_file() {
        return Ok(());
    }
    create_dir_all(blob.parent().unwrap_or(blob_root))?;
    if fs::hard_link(staged, &blob).is_err() {
        fs::copy(staged, &blob).map_err(|source| FinalizeError::Io {
            path: blob.clone(),
            source,
        })?;
    }
    stamp_content_mtime(&blob, sha)
}

/// Overwrites committed files with caller-supplied template contents,
/// preserving the uploaded original beside the version.
pub fn apply_templates(
    templates: &BTreeMap<String, String>,
    stage_root: &Path,
    files: &mut BTreeMap<String, FileMeta>,
) -> Result<()> {
    if templates.is_empty() {
        return Ok(());
    }
    if templates.len() > TEMPLATE_VARIANT_FILE_LIMIT {
        return invalid(
            "invalid_template_files",
            "template_files supports up to 100 entries.",
        );
    }
    for (path, content) in templates {
        validate_relative_path(path)?;
        if content.len() > TEMPLATE_MAX_BYTES || !files.contains_key(path) {
            return invalid(
                "invalid_template_files",
                format!("Invalid template file {path}."),
            );
        }
        let target = stage_root.join("files").join(path);
        let original = stage_root.join("files-original").join(path);
        create_dir_all(original.parent().unwrap_or(stage_root))?;
        fs::copy(&target, &original).map_err(|source| FinalizeError::Io {
            path: original,
            source,
        })?;
        write_generated(
            &stage_root.join("files"),
            files,
            path,
            content.as_bytes(),
            None,
        )?;
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::finalize::sha256;
    use serde_json::json;
    use tempfile::tempdir;

    /// Seeds `count` blobs directly into the space CAS and returns the
    /// `retained_files` manifest that publishes them unchanged.
    fn seed_retained_cas(private: &Path, count: usize) -> Vec<Value> {
        let blobs = private.join("spaces/s/blobs");
        (0..count)
            .map(|index| {
                let bytes = format!("retained body {index}\n").repeat(8 + index % 5);
                let hash = sha256(bytes.as_bytes());
                let blob = blobs.join(&hash[..2]).join(&hash);
                fs::create_dir_all(blob.parent().unwrap()).unwrap();
                fs::write(&blob, &bytes).unwrap();
                json!({
                    "path": format!("docs/page-{index:04}.html"),
                    "size": bytes.len(),
                    "sha256": hash,
                })
            })
            .collect()
    }

    /// Puts bytes in the CAS the way ingest does — hashed on arrival, stored
    /// under their own digest — and returns the manifest entry plus the
    /// `accepted` pair the publish session records for it.
    fn accept(private: &Path, path: &str, bytes: &[u8]) -> (Value, (String, Value)) {
        let hash = sha256(bytes);
        let blob = private.join(format!("spaces/s/blobs/{}/{hash}", &hash[..2]));
        fs::create_dir_all(blob.parent().unwrap()).unwrap();
        fs::write(&blob, bytes).unwrap();
        (
            json!({"path": path, "size": bytes.len(), "sha256": hash}),
            (hash, json!(bytes.len())),
        )
    }

    /// A publish session in the shape the durable session record hands over.
    fn session(manifest: Vec<Value>, accepted: Vec<(String, Value)>) -> Value {
        json!({
            "manifest": manifest,
            "accepted": accepted.into_iter().collect::<serde_json::Map<_, _>>(),
        })
    }

    /// Every path under `root`, with the size of each file, so a subtree can be
    /// compared before and after a run.
    fn subtree(root: &Path) -> BTreeMap<String, u64> {
        walkdir::WalkDir::new(root)
            .follow_links(false)
            .into_iter()
            .filter_map(std::result::Result::ok)
            .map(|entry| {
                let relative = entry
                    .path()
                    .strip_prefix(root)
                    .unwrap_or(entry.path())
                    .to_string_lossy()
                    .into_owned();
                let size = if entry.file_type().is_file() {
                    entry.metadata().map(|meta| meta.len()).unwrap_or(0)
                } else {
                    u64::MAX
                };
                (relative, size)
            })
            .collect()
    }

    /// Finalize writes nothing into the CAS to stage a version: ingest already
    /// put every accepted byte there under its own hash, so the only work owed
    /// is a hardlink into the working tree.
    ///
    /// The read-only CAS directory makes "does not write" an observable outcome
    /// rather than a counted call — any create or rename under it fails with
    /// EACCES for an unprivileged runner.
    #[cfg(unix)]
    #[test]
    fn staging_a_version_writes_nothing_into_the_cas() {
        use std::os::unix::fs::{MetadataExt, PermissionsExt};

        let temp = tempdir().unwrap();
        let private = temp.path().join("storage");
        let retained = seed_retained_cas(&private, 24);
        let (entry, accepted) = accept(&private, "index.html", b"<p>fresh</p>");
        let blobs = private.join("spaces/s/blobs");
        let stage = private.join("spaces/s/versions/.v.rust-finalizing");
        fs::create_dir_all(stage.join("files")).unwrap();
        let before = subtree(&blobs);
        fs::set_permissions(&blobs, fs::Permissions::from_mode(0o555)).unwrap();

        let mut files = BTreeMap::new();
        let mut record = session(vec![entry], vec![accepted]);
        record["reusable_version_id"] = json!("prev");
        record["retained_files"] = json!(retained.clone());
        let result = commit_session_files("s", &record, &private, &stage, &mut files);

        fs::set_permissions(&blobs, fs::Permissions::from_mode(0o755)).unwrap();
        result.unwrap();
        assert_eq!(files.len(), retained.len() + 1);
        assert_eq!(subtree(&blobs), before);
        for entry in &retained {
            let path = entry["path"].as_str().unwrap();
            let hash = entry["sha256"].as_str().unwrap();
            let blob = blobs.join(&hash[..2]).join(hash);
            let staged = stage.join("files").join(path);
            assert_eq!(fs::read(&staged).unwrap(), fs::read(&blob).unwrap());
            assert_eq!(
                fs::metadata(&staged).unwrap().ino(),
                fs::metadata(&blob).unwrap().ino(),
                "{path} must be hardlinked to its CAS blob, not copied"
            );
        }
        assert_eq!(
            fs::read(stage.join("files/index.html")).unwrap(),
            b"<p>fresh</p>"
        );
    }

    /// nginx serves an accelerated response and stamps its own
    /// `ETag: "<hex mtime>-<hex size>"` from the placed file, never seeing our
    /// sha256. So the placed file's mtime has to be the content-derived one the
    /// metadata already advertises, not a clock reading: otherwise two
    /// same-size bodies published in one second share an ETag and a
    /// revalidating visitor is handed the superseded one. Covers both placement
    /// sites — the CAS hardlink and a pipeline-generated file.
    #[test]
    fn placed_files_carry_the_content_derived_mtime_their_metadata_advertises() {
        let temp = tempdir().unwrap();
        let private = temp.path().join("storage");
        let (entry, accepted) = accept(&private, "index.html", b"<html><body>placed</body></html>");
        let stage = private.join("spaces/s/versions/.v.rust-finalizing");
        fs::create_dir_all(stage.join("files")).unwrap();

        let mut files = BTreeMap::new();
        commit_session_files(
            "s",
            &session(vec![entry], vec![accepted]),
            &private,
            &stage,
            &mut files,
        )
        .unwrap();

        let on_disk = fs::metadata(stage.join("files/index.html"))
            .unwrap()
            .modified()
            .unwrap()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .as_secs();
        assert_eq!(on_disk, files["index.html"].mtime);

        // A generated file is placed by a different writer and must agree.
        write_generated(
            &stage.join("files"),
            &mut files,
            "listing.html",
            b"<html><body>generated</body></html>",
            Some("text/html; charset=utf-8"),
        )
        .unwrap();
        let generated = fs::metadata(stage.join("files/listing.html"))
            .unwrap()
            .modified()
            .unwrap()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .as_secs();
        assert_eq!(generated, files["listing.html"].mtime);
        assert_ne!(generated, on_disk);
    }

    /// A staged file costs a hardlink: its bytes are never read.
    ///
    /// Read permission on the CAS object is the barrier that makes "never read"
    /// an observable outcome rather than a counted call — `link(2)` and
    /// `stat(2)` need none, `open(2)` for reading needs it.
    ///
    /// A privileged runner ignores the mode bits, so the barrier only bites for
    /// an ordinary one (the Rust workspace's CI job runs directly on the GitHub
    /// runner user). The identity assertions below hold either way.
    #[cfg(unix)]
    #[test]
    fn accepted_blobs_are_staged_without_reading_their_bytes() {
        use std::os::unix::fs::{MetadataExt, PermissionsExt};

        let temp = tempdir().unwrap();
        let private = temp.path().join("storage");
        let blobs = private.join("spaces/s/blobs");
        let mut manifest = Vec::new();
        let mut accepted = Vec::new();
        for index in 0..12 {
            let body = format!("<p>page {index}</p>");
            let (entry, pair) = accept(
                &private,
                &format!("docs/page-{index:04}.html"),
                body.as_bytes(),
            );
            manifest.push(entry);
            accepted.push(pair);
        }
        let stage = private.join("spaces/s/versions/.v.rust-finalizing");
        fs::create_dir_all(stage.join("files")).unwrap();
        for (hash, _) in &accepted {
            let blob = blobs.join(&hash[..2]).join(hash);
            fs::set_permissions(&blob, fs::Permissions::from_mode(0o000)).unwrap();
        }

        let mut files = BTreeMap::new();
        commit_session_files(
            "s",
            &session(manifest.clone(), accepted.clone()),
            &private,
            &stage,
            &mut files,
        )
        .unwrap();

        assert_eq!(files.len(), manifest.len());
        for entry in &manifest {
            let path = entry["path"].as_str().unwrap();
            let hash = entry["sha256"].as_str().unwrap();
            let blob = blobs.join(&hash[..2]).join(hash);
            assert_eq!(
                fs::metadata(stage.join("files").join(path)).unwrap().ino(),
                fs::metadata(&blob).unwrap().ino(),
                "{path} must be hardlinked to its CAS blob"
            );
            assert_eq!(files[path].sha256, hash);
        }
        for (hash, _) in &accepted {
            let blob = blobs.join(&hash[..2]).join(hash);
            fs::set_permissions(&blob, fs::Permissions::from_mode(0o644)).unwrap();
        }
    }

    /// A retained set large enough to be staged across threads lands exactly
    /// the same tree, and still blames the first bad path in manifest order
    /// rather than whichever thread happened to reach one first.
    #[test]
    fn a_retained_set_staged_across_threads_lands_in_order() {
        let count = STAGE_PARALLEL_THRESHOLD * 3;
        let temp = tempdir().unwrap();
        let private = temp.path().join("storage");
        let retained = seed_retained_cas(&private, count);
        let stage = private.join("spaces/s/versions/.v.rust-finalizing");
        fs::create_dir_all(stage.join("files")).unwrap();

        let mut files = BTreeMap::new();
        commit_session_files(
            "s",
            &json!({
                "reusable_version_id": "prev",
                "retained_files": retained.clone(),
            }),
            &private,
            &stage,
            &mut files,
        )
        .unwrap();
        assert_eq!(files.len(), count);
        for entry in &retained {
            let path = entry["path"].as_str().unwrap();
            let hash = entry["sha256"].as_str().unwrap();
            assert_eq!(files[path].sha256, hash);
            assert_eq!(
                fs::read(stage.join("files").join(path)).unwrap(),
                fs::read(private.join(format!("spaces/s/blobs/{}/{hash}", &hash[..2]))).unwrap()
            );
        }

        // Break two paths, one early and one late. The early one is reported.
        let mut broken = retained.clone();
        broken[7]["size"] = json!(999_999);
        broken[count - 3]["size"] = json!(999_998);
        let error = commit_session_files(
            "s",
            &json!({
                "reusable_version_id": "prev",
                "retained_files": broken,
            }),
            &private,
            &private.join("spaces/s/versions/.other.rust-finalizing"),
            &mut BTreeMap::new(),
        )
        .unwrap_err();
        match error {
            FinalizeError::Invalid { code, message, .. } => {
                assert_eq!(code, "version_file_size_mismatch");
                assert!(
                    message.contains(retained[7]["path"].as_str().unwrap()),
                    "expected the first bad path in manifest order, got: {message}"
                );
            }
            other => panic!("unexpected error: {other}"),
        }
    }

    /// The `stat` a retained commit does costs nothing and still refuses a CAS
    /// object whose length is not the length the manifest declares.
    #[test]
    fn retained_finalize_rejects_a_cas_object_of_the_wrong_length() {
        let temp = tempdir().unwrap();
        let private = temp.path().join("storage");
        let hash = sha256(b"declared bytes");
        let blob = private.join(format!("spaces/s/blobs/{}/{hash}", &hash[..2]));
        fs::create_dir_all(blob.parent().unwrap()).unwrap();
        fs::write(&blob, b"declared bytes but longer").unwrap();
        let stage = private.join("spaces/s/versions/.v.rust-finalizing");
        fs::create_dir_all(stage.join("files")).unwrap();

        let error = commit_session_files(
            "s",
            &json!({
                "reusable_version_id": "prev",
                "retained_files": [{"path":"index.html","size":14,"sha256":hash}],
            }),
            &private,
            &stage,
            &mut BTreeMap::new(),
        )
        .unwrap_err();

        match error {
            FinalizeError::Invalid { code, .. } => assert_eq!(code, "version_file_size_mismatch"),
            other => panic!("unexpected error: {other}"),
        }
        assert!(!stage.join("files/index.html").exists());
    }

    /// Finalize does not re-hash an accepted blob, so the session is the
    /// authority on what arrived: a manifest path whose sha the session never
    /// accepted, or accepted at another length, or whose CAS object is not
    /// there at the declared length, is a path this publish does not have. All
    /// three land in ONE structured answer, which is what a resuming caller
    /// re-negotiates against.
    #[test]
    fn a_manifest_path_the_session_never_accepted_reports_as_incomplete() {
        let temp = tempdir().unwrap();
        let private = temp.path().join("storage");
        let stage = private.join("spaces/s/versions/.v.rust-finalizing");
        fs::create_dir_all(stage.join("files")).unwrap();
        let (present, accepted) = accept(&private, "present.html", b"<p>here</p>");
        let (wrong_size, _) = accept(&private, "short.html", b"<p>len</p>");
        let never = json!({
            "path": "never.html",
            "size": 4,
            "sha256": sha256(b"nope"),
        });
        // Declared at a length the session accepted for other bytes entirely.
        let mut lying = wrong_size.clone();
        lying["size"] = json!(9_999);

        let error = commit_session_files(
            "s",
            &session(vec![present, never, lying], vec![accepted]),
            &private,
            &stage,
            &mut BTreeMap::new(),
        )
        .unwrap_err();

        match error {
            FinalizeError::Invalid { code, details, .. } => {
                assert_eq!(code, "version_upload_incomplete");
                assert_eq!(
                    details,
                    Some(json!({
                        "missingPaths": ["never.html", "short.html"],
                        "missingCount": 2
                    }))
                );
            }
            other => panic!("unexpected error: {other}"),
        }
        // Nothing partially staged: the answer arrives before any placement.
        assert!(!stage.join("files/present.html").exists());
    }

    #[test]
    fn a_non_array_session_manifest_fails_closed() {
        let temp = tempdir().unwrap();
        let private = temp.path().join("storage");
        let stage = private.join("spaces/s/versions/.v.rust-finalizing");
        for record in [
            json!({ "manifest": "index.html" }),
            json!({ "manifest": [], "accepted": [] }),
        ] {
            let error = commit_session_files("s", &record, &private, &stage, &mut BTreeMap::new())
                .unwrap_err();
            match error {
                FinalizeError::Invalid { code, .. } => assert_eq!(code, "version_session_invalid"),
                other => panic!("unexpected error: {other}"),
            }
        }
    }

    // A settings-only version legitimately declares no paths at all: it commits
    // retained bytes alone, so an empty manifest must still succeed.
    #[test]
    fn an_empty_session_manifest_commits_nothing_and_succeeds() {
        let temp = tempdir().unwrap();
        let private = temp.path().join("storage");
        let stage = private.join("spaces/s/versions/.v.rust-finalizing");
        fs::create_dir_all(stage.join("files")).unwrap();
        let mut files = BTreeMap::new();
        commit_session_files(
            "s",
            &json!({ "manifest": [], "accepted": {} }),
            &private,
            &stage,
            &mut files,
        )
        .unwrap();
        assert!(files.is_empty());
    }

    #[test]
    fn transforms_never_mutate_content_addressed_source_bytes() {
        let original: &[u8] = b"<html><body>{{ value }}</body></html>";
        let temp = tempdir().unwrap();
        let private = temp.path().join(".stattic/storage");
        let (entry, accepted) = accept(&private, "index.html", original);
        let hash = sha256(original);
        let stage = private.join("spaces/s/versions/.v.rust-finalizing");
        fs::create_dir_all(stage.join("files")).unwrap();
        let mut files = BTreeMap::new();
        commit_session_files(
            "s",
            &session(vec![entry], vec![accepted]),
            &private,
            &stage,
            &mut files,
        )
        .unwrap();
        apply_templates(
            &BTreeMap::from([(
                "index.html".to_string(),
                "<html><body>resolved</body></html>".to_string(),
            )]),
            &stage,
            &mut files,
        )
        .unwrap();
        assert_eq!(
            fs::read(private.join(format!("spaces/s/blobs/{}/{hash}", &hash[..2]))).unwrap(),
            original
        );
        assert_eq!(
            fs::read(stage.join("files-original/index.html")).unwrap(),
            original
        );
        assert_eq!(
            fs::read_to_string(stage.join("files/index.html")).unwrap(),
            "<html><body>resolved</body></html>"
        );
    }
}
