[package]
name = "stattic-runtime-core"
version = "0.1.0"
edition.workspace = true
publish = false

[dependencies]
bcrypt.workspace = true
lol_html.workspace = true
mime_guess.workspace = true
pulldown-cmark.workspace = true
regex.workspace = true
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_yaml.workspace = true
sha2 = "0.10"
unicode-normalization.workspace = true
url.workspace = true
walkdir.workspace = true

[target.'cfg(not(target_family = "wasm"))'.dependencies]
stattic-zero-runner = { path = "../stattic-zero-runner" }

[dev-dependencies]
tempfile = "3"
