use std::env;
use std::fs;
use std::path::PathBuf;

const CAPABILITIES: [(&str, u8); 6] = [
    ("db", 1 << 0),
    ("fetch", 1 << 1),
    ("auth", 1 << 2),
    ("env", 1 << 3),
    ("realtime", 1 << 4),
    ("logging", 1 << 5),
];

fn main() {
    println!("cargo:rerun-if-changed=src/templates/runtime-template.js");

    let template_path = PathBuf::from("src/templates/runtime-template.js");
    let template = fs::read_to_string(&template_path)
        .unwrap_or_else(|error| panic!("failed to read {}: {error}", template_path.display()));

    let mut generated = String::from(
        "// Generated by build.rs. Do not edit.\n\
         pub(crate) fn runtime_prelude_for_capability_mask(mask: u8) -> &'static str {\n\
         match mask & 63 {\n",
    );
    for mask in 0u8..64 {
        let rendered = render_template(&template, mask);
        generated.push_str(&format!("        {mask} => {rendered:?},\n"));
    }
    generated.push_str("        _ => unreachable!(),\n    }\n}\n");

    let out_dir = PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR set by Cargo"));
    fs::write(out_dir.join("zero_runtime_templates.rs"), generated)
        .expect("write generated Zero runtime templates");
}

fn render_template(template: &str, mask: u8) -> String {
    let mut output = String::with_capacity(template.len());
    let mut include_stack: Vec<bool> = Vec::new();

    for line in template.lines() {
        let trimmed = line.trim();
        if let Some(name) = trimmed.strip_prefix("// @stattic-if ") {
            let enabled = capability_enabled(name.trim(), mask)
                .unwrap_or_else(|| panic!("unknown Zero runtime template capability: {name}"));
            let parent_enabled = include_stack.iter().all(|enabled| *enabled);
            include_stack.push(parent_enabled && enabled);
            continue;
        }
        if trimmed == "// @stattic-endif" {
            include_stack
                .pop()
                .expect("unmatched @stattic-endif in Zero runtime template");
            continue;
        }
        if include_stack.iter().all(|enabled| *enabled) {
            output.push_str(line);
            output.push('\n');
        }
    }

    assert!(
        include_stack.is_empty(),
        "unterminated @stattic-if block in Zero runtime template"
    );
    output
}

fn capability_enabled(name: &str, mask: u8) -> Option<bool> {
    CAPABILITIES
        .iter()
        .find_map(|(capability, bit)| (*capability == name).then_some(mask & bit != 0))
}
