use crate::artifacts::EndpointCapabilities;

include!(concat!(env!("OUT_DIR"), "/zero_runtime_templates.rs"));

pub(crate) fn render_endpoint_program(
    endpoint_source: &str,
    capabilities: &EndpointCapabilities,
) -> String {
    let prelude = runtime_prelude_for_capability_mask(capability_mask(capabilities));
    let mut program = String::with_capacity(endpoint_source.len() + prelude.len() + 64);
    program.push_str("// Generated by stattic-zero-runner. Do not edit by hand.\n");
    program.push_str(prelude);
    program.push_str("\n// Endpoint module\n");
    program.push_str(endpoint_source);
    if !endpoint_source.ends_with('\n') {
        program.push('\n');
    }
    program
}

fn capability_mask(capabilities: &EndpointCapabilities) -> u8 {
    let mut mask = 0u8;
    if capabilities.db {
        mask |= 1 << 0;
    }
    if capabilities.fetch {
        mask |= 1 << 1;
    }
    if capabilities.auth {
        mask |= 1 << 2;
    }
    if capabilities.env {
        mask |= 1 << 3;
    }
    if capabilities.realtime {
        mask |= 1 << 4;
    }
    if capabilities.logging {
        mask |= 1 << 5;
    }
    mask
}
