use crate::artifacts::EndpointCapabilities;

/// The prelude source, rendered per capability set.
///
/// This runs in the `prepare` command — once per endpoint at publish — and
/// never on a request. It used to be a build-time table of every capability
/// combination; that bought nothing at runtime and doubled with each new
/// capability, so the renderer runs directly instead.
const RUNTIME_TEMPLATE: &str = include_str!("templates/runtime-template.js");

pub(crate) fn render_endpoint_program(
    endpoint_source: &str,
    capabilities: &EndpointCapabilities,
) -> String {
    let prelude = render_template(RUNTIME_TEMPLATE, capabilities);
    let mut program = String::with_capacity(endpoint_source.len() + prelude.len() + 64);
    program.push_str("// Generated by stattic-zero-runner. Do not edit by hand.\n");
    program.push_str(&prelude);
    program.push_str("\n// Endpoint module\n");
    program.push_str(endpoint_source);
    if !endpoint_source.ends_with('\n') {
        program.push('\n');
    }
    program
}

fn render_template(template: &str, capabilities: &EndpointCapabilities) -> String {
    let mut output = String::with_capacity(template.len());
    let mut include_stack: Vec<bool> = Vec::new();

    for line in template.lines() {
        let trimmed = line.trim();
        if let Some(name) = trimmed.strip_prefix("// @stattic-if ") {
            let enabled = capability_enabled(name.trim(), capabilities)
                .unwrap_or_else(|| panic!("unknown Zero runtime template capability: {name}"));
            let parent_enabled = include_stack.iter().all(|enabled| *enabled);
            include_stack.push(parent_enabled && enabled);
            continue;
        }
        if trimmed == "// @stattic-endif" {
            include_stack
                .pop()
                .expect("unmatched @stattic-endif in Zero runtime template");
            continue;
        }
        if include_stack.iter().all(|enabled| *enabled) {
            output.push_str(line);
            output.push('\n');
        }
    }

    assert!(
        include_stack.is_empty(),
        "unterminated @stattic-if block in Zero runtime template"
    );
    output
}

fn capability_enabled(name: &str, capabilities: &EndpointCapabilities) -> Option<bool> {
    match name {
        "db" => Some(capabilities.db),
        "fetch" => Some(capabilities.fetch),
        "auth" => Some(capabilities.auth),
        "env" => Some(capabilities.env),
        "realtime" => Some(capabilities.realtime),
        "logging" => Some(capabilities.logging),
        // One block covers all three services: the prelude only installs the
        // bridge, and which services a handler may actually reach is decided by
        // the broker's grant, not by what the bridge can encode.
        "services" => Some(capabilities.any_service()),
        _ => None,
    }
}
