// @generated by `cargo run -p stattic-runtime-compiler --bin protocol-codegen`.
// Rust `protocol.rs` and `config/current.rs` are the only editable authorities.

export const FINALIZER_PROTOCOL = {
  config: {
    current: {
      canonicalFile: "spacefast.jsonc",
      aliasFiles: [
        "sf.jsonc",
        "spacefast.json",
        "sf.json",
        ".sf/sf.json",
        ".sf/config.jsonc",
        ".sf/config.json",
      ],
      acceptedFiles: [
        "spacefast.jsonc",
        "sf.jsonc",
        "spacefast.json",
        "sf.json",
        ".sf/sf.json",
        ".sf/config.jsonc",
        ".sf/config.json",
      ],
    },
    strictV1: {
      canonicalFile: "spacefast.jsonc",
      aliasFiles: [
        "sf.jsonc",
        "spacefast.json",
        "sf.json",
        ".sf/sf.json",
        ".sf/config.jsonc",
        ".sf/config.json",
      ],
      acceptedFiles: [
        "spacefast.jsonc",
        "sf.jsonc",
        "spacefast.json",
        "sf.json",
        ".sf/sf.json",
        ".sf/config.jsonc",
        ".sf/config.json",
      ],
    },
  },
  spaceConfigSchema: {
    $id: "https://spacefast.com/schemas/sf.json",
    $schema: "http://json-schema.org/draft-07/schema#",
    additionalProperties: true,
    properties: {
      $schema: {
        type: "string",
      },
      access: {
        additionalProperties: false,
        properties: {
          rules: {
            items: {
              additionalProperties: false,
              properties: {
                auth: {
                  additionalProperties: false,
                  properties: {
                    acquire: {
                      items: {
                        oneOf: [
                          {
                            additionalProperties: false,
                            properties: {
                              ref: {
                                minLength: 1,
                                type: "string",
                              },
                              transport: {
                                enum: ["basic", "form"],
                              },
                              type: {
                                const: "password",
                              },
                              username: {
                                minLength: 1,
                                type: "string",
                              },
                            },
                            required: ["type", "ref", "transport"],
                            type: "object",
                          },
                          {
                            additionalProperties: false,
                            properties: {
                              label: {
                                minLength: 1,
                                type: "string",
                              },
                              type: {
                                const: "login",
                              },
                              url: {
                                minLength: 1,
                                type: "string",
                              },
                            },
                            required: ["type", "url"],
                            type: "object",
                          },
                        ],
                      },
                      type: "array",
                    },
                    issuers: {
                      items: {
                        additionalProperties: false,
                        properties: {
                          alg: {
                            const: "EdDSA",
                          },
                          grantNamespaces: {
                            items: {
                              minLength: 1,
                              type: "string",
                            },
                            minItems: 1,
                            type: "array",
                          },
                          kid: {
                            minLength: 1,
                            type: "string",
                          },
                          publicKey: {
                            minLength: 1,
                            type: "string",
                          },
                        },
                        required: ["kid", "alg", "publicKey", "grantNamespaces"],
                        type: "object",
                      },
                      type: "array",
                    },
                    requiredGrants: {
                      items: {
                        maxLength: 255,
                        minLength: 1,
                        type: "string",
                      },
                      minItems: 1,
                      type: "array",
                    },
                  },
                  required: ["requiredGrants"],
                  type: "object",
                },
                effect: {
                  enum: ["allow", "deny", "challenge"],
                },
                expiresAt: {
                  minimum: 0,
                  type: "integer",
                },
                id: {
                  minLength: 1,
                  type: "string",
                },
                managedBy: {
                  enum: ["sharing", "firewall", "file_share", "cast_reviewer", "team_default"],
                },
                match: {
                  additionalProperties: false,
                  properties: {
                    agent: {
                      minLength: 1,
                      type: "string",
                    },
                    channel: {
                      minLength: 1,
                      type: "string",
                    },
                    country: {
                      maxLength: 2,
                      minLength: 2,
                      type: "string",
                    },
                    header: {
                      additionalProperties: false,
                      properties: {
                        name: {
                          minLength: 1,
                          type: "string",
                        },
                        value: {
                          type: "string",
                        },
                      },
                      required: ["name", "value"],
                      type: "object",
                    },
                    host: {
                      minLength: 1,
                      type: "string",
                    },
                    hostPattern: {
                      minLength: 1,
                      type: "string",
                    },
                    hostTemplate: {
                      minLength: 1,
                      type: "string",
                    },
                    ipCidrs: {
                      items: {
                        minLength: 1,
                        type: "string",
                      },
                      maxItems: 50,
                      type: "array",
                    },
                    pathPattern: {
                      minLength: 1,
                      type: "string",
                    },
                  },
                  type: "object",
                },
                message: {
                  minLength: 1,
                  type: "string",
                },
                reasonCode: {
                  minLength: 1,
                  type: "string",
                },
              },
              required: ["effect"],
              type: "object",
            },
            maxItems: 100,
            type: "array",
          },
        },
        type: "object",
      },
      build: {
        additionalProperties: false,
        properties: {
          allowUnsupportedPlatformFeatures: {
            type: "boolean",
          },
          buildCommand: {
            oneOf: [
              {
                pattern: "\\S",
                type: "string",
              },
              {
                type: "null",
              },
            ],
          },
          frameworkPreset: {
            oneOf: [
              {
                pattern: "\\S",
                type: "string",
              },
              {
                type: "null",
              },
            ],
          },
          ignoredBuildCommand: {
            oneOf: [
              {
                pattern: "\\S",
                type: "string",
              },
              {
                type: "null",
              },
            ],
          },
          installCommand: {
            oneOf: [
              {
                pattern: "\\S",
                type: "string",
              },
              {
                type: "null",
              },
            ],
          },
          installDirectory: {
            oneOf: [
              {
                pattern: "\\S",
                type: "string",
              },
              {
                type: "null",
              },
            ],
          },
          outputDirectory: {
            oneOf: [
              {
                pattern: "\\S",
                type: "string",
              },
              {
                type: "null",
              },
            ],
          },
          platformPreset: {
            oneOf: [
              {
                pattern: "\\S",
                type: "string",
              },
              {
                type: "null",
              },
            ],
          },
          rootDirectory: {
            oneOf: [
              {
                pattern: "\\S",
                type: "string",
              },
              {
                type: "null",
              },
            ],
          },
          timeoutSeconds: {
            maximum: 7200,
            minimum: 60,
            type: "integer",
          },
        },
        type: "object",
      },
      cleanUrls: {
        type: "boolean",
      },
      fallback: {
        oneOf: [
          {
            minLength: 1,
            type: "string",
          },
          {
            additionalProperties: false,
            properties: {
              path: {
                minLength: 1,
                type: "string",
              },
              status: {
                maximum: 599,
                minimum: 100,
                type: "integer",
              },
            },
            required: ["path", "status"],
            type: "object",
          },
        ],
      },
      index: {
        oneOf: [
          {
            minLength: 1,
            type: "string",
          },
          {
            const: false,
          },
        ],
      },
      listing: {
        type: "boolean",
      },
      markdownNegotiation: {
        type: "boolean",
      },
      meta: {
        additionalProperties: false,
        properties: {
          description: {
            maxLength: 1000,
            type: "string",
          },
          image: {
            maxLength: 2000,
            type: "string",
          },
          title: {
            maxLength: 300,
            minLength: 1,
            type: "string",
          },
        },
        type: "object",
      },
      placement: {
        additionalProperties: false,
        properties: {
          burstable: {
            type: "boolean",
          },
          mode: {
            enum: ["shared", "dedicated"],
          },
          region: {
            pattern: "\\S",
            type: "string",
          },
        },
        type: "object",
      },
      space: {
        minLength: 1,
        type: "string",
      },
      superpowers: {
        additionalProperties: false,
        properties: {
          disable_all_injection: {
            type: "boolean",
          },
          enabled: {
            type: "boolean",
          },
          googleAnalytics: {
            additionalProperties: false,
            properties: {
              enabled: {
                type: "boolean",
              },
              measurementId: {
                maxLength: 64,
                type: "string",
              },
            },
            type: "object",
          },
          googleTagManager: {
            additionalProperties: false,
            properties: {
              containerId: {
                maxLength: 64,
                type: "string",
              },
              enabled: {
                type: "boolean",
              },
            },
            type: "object",
          },
          javascriptTags: {
            items: {
              additionalProperties: false,
              properties: {
                code: {
                  maxLength: 8192,
                  type: "string",
                },
                enabled: {
                  type: "boolean",
                },
                id: {
                  maxLength: 128,
                  type: "string",
                },
                name: {
                  maxLength: 160,
                  type: "string",
                },
              },
              required: ["code"],
              type: "object",
            },
            maxItems: 16,
            type: "array",
          },
          tags: {
            additionalProperties: false,
            properties: {
              inheritance: {
                additionalProperties: false,
                properties: {
                  inherited: {
                    type: "boolean",
                  },
                  overrides: {
                    items: {
                      additionalProperties: false,
                      properties: {
                        disabled: {
                          type: "boolean",
                        },
                        reason: {
                          oneOf: [
                            {
                              maxLength: 500,
                              type: "string",
                            },
                            {
                              type: "null",
                            },
                          ],
                        },
                        tagId: {
                          minLength: 1,
                          type: "string",
                        },
                      },
                      required: ["tagId"],
                      type: "object",
                    },
                    maxItems: 128,
                    type: "array",
                  },
                },
                type: "object",
              },
              requireReview: {
                type: "boolean",
              },
            },
            type: "object",
          },
        },
        type: "object",
      },
      templates: {
        items: {
          minLength: 1,
          type: "string",
        },
        maxItems: 100,
        type: "array",
      },
      theme: {
        additionalProperties: false,
        properties: {
          accent: {
            maxLength: 64,
            pattern:
              "^(?:#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{4}|[0-9a-fA-F]{6}|[0-9a-fA-F]{8})|rgba?\\([0-9.,\\s%/]{1,64}\\)|hsla?\\([0-9.,\\s%deg/]{1,64}\\)|[a-zA-Z]{3,30})$",
            type: "string",
          },
          background: {
            maxLength: 64,
            pattern:
              "^(?:#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{4}|[0-9a-fA-F]{6}|[0-9a-fA-F]{8})|rgba?\\([0-9.,\\s%/]{1,64}\\)|hsla?\\([0-9.,\\s%deg/]{1,64}\\)|[a-zA-Z]{3,30})$",
            type: "string",
          },
          font: {
            maxLength: 256,
            minLength: 1,
            pattern: "^[A-Za-z0-9 ,'\\\"-]+$",
            type: "string",
          },
          hideSpacefastBranding: {
            type: "boolean",
          },
          logo: {
            maxLength: 2000,
            pattern: "^(?:https://[^\\s\\\"'<>\\\\]+|/[^\\s\\\"'<>\\\\]*)$",
            type: "string",
          },
          name: {
            maxLength: 120,
            minLength: 1,
            type: "string",
          },
        },
        type: "object",
      },
    },
    title: "Spacefast space configuration (sf.jsonc)",
    type: "object",
  },
  limits: {
    configFileMaxBytes: 262144,
    configOverlayMaxBytes: 16384,
    configTemplateLimit: 100,
    configMetaTitleMaxChars: 300,
    configMetaDescriptionMaxChars: 1000,
    configMetaImageMaxChars: 2000,
    configInjectSnippetMaxBytes: 8192,
    configInjectSnippetLimit: 16,
    configAccessRuleLimit: 100,
    configPagesColorMaxChars: 64,
    configPagesLogoMaxChars: 2000,
    configPagesNameMaxChars: 120,
    configPagesFontFamilyMaxChars: 256,
    configBuildTimeoutMinSeconds: 60,
    configBuildTimeoutMaxSeconds: 7200,
    configFallbackStatusMin: 100,
    configFallbackStatusMax: 599,
    configSuperpowersIntegrationIdMaxChars: 64,
    configSuperpowersTagIdMaxChars: 128,
    configSuperpowersTagNameMaxChars: 160,
    configSuperpowersOverrideLimit: 128,
    configSuperpowersOverrideReasonMaxChars: 500,
    templateMaxBytes: 2097152,
    templateVariantFileLimit: 100,
    templateVariantRouteLimit: 8,
    templateVariantRouteNameMaxChars: 128,
    pageMaxBytes: 2097152,
    gateThemeFileMaxBytes: 65536,
    gateThemeVarsMaxBytes: 8192,
    spaceThemeCssMaxBytes: 16384,
    spaceThemePresetLimit: 64,
    spaceThemeSlugMaxChars: 64,
    spaceThemeValueMaxChars: 128,
    spaceThemeNameMaxChars: 128,
    spaceThemeSizeMaxChars: 64,
    spaceThemeFontFamilyMaxChars: 256,
    themeJsonFontFamilyLimit: 32,
    zeroBundleMaxBytes: 786432,
    zeroBundleLimit: 8,
    zeroStaticFileLimit: 16,
    zeroEntryLimit: 128,
    zeroSourceMaxBytes: 2097152,
    zeroIdMaxChars: 256,
    zeroRoutePathMaxChars: 2048,
    zeroEntryNameMaxChars: 128,
    zeroContentTypeMaxChars: 255,
  },
  markers: {
    challenge: "<!--spacefast:slot:challenge:v1-->",
    deny: "<!--spacefast:slot:deny:v1-->",
    layout: "<!--spacefast:slot:layout-content:v1-->",
    badge: "<!--spacefast:slot:badge:v1-->",
  },
  paths: {
    challenge: "401.html",
    deny: "403.html",
    layout: ".spacefast/templates/layout.html",
  },
} as const;

export type FinalizerProtocolMetadata = typeof FINALIZER_PROTOCOL;

export type SpaceTheme = {
  accent?: string;
  background?: string;
  logo?: string;
  name?: string;
  font?: string;
  hideSpacefastBranding?: boolean;
};

export type SpaceBuildSettings = {
  rootDirectory?: string | null;
  installDirectory?: string | null;
  installCommand?: string | null;
  buildCommand?: string | null;
  outputDirectory?: string | null;
  ignoredBuildCommand?: string | null;
  frameworkPreset?: string | null;
  platformPreset?: string | null;
  allowUnsupportedPlatformFeatures?: boolean;
  timeoutSeconds?: number;
};

export type SpacePlacementConfig = {
  region?: string;
  mode?: "shared" | "dedicated";
  burstable?: boolean;
};

export type SpaceConfig = {
  index?: string | false;
  fallback?: string | { path: string; status: number };
  cleanUrls?: boolean;
  listing?: boolean;
  meta?: { title?: string; description?: string; image?: string };
  superpowers?: {
    enabled?: boolean;
    disable_all_injection?: boolean;
    googleAnalytics?: { enabled?: boolean; measurementId?: string };
    googleTagManager?: { enabled?: boolean; containerId?: string };
    javascriptTags?: Array<{ id?: string; name?: string; enabled?: boolean; code: string }>;
    tags?: {
      inheritance?: {
        inherited?: boolean;
        overrides?: Array<{ tagId: string; disabled?: boolean; reason?: string | null }>;
      };
      requireReview?: boolean;
    };
  };
  templates?: string[];
  theme?: SpaceTheme;
  build?: SpaceBuildSettings;
  placement?: SpacePlacementConfig;
  markdownNegotiation?: boolean;
  experimental_gutenberg?: boolean;
  inject?: { head?: string[]; bodyStart?: string[]; bodyEnd?: string[]; noscript?: string[] };
};

export type SpaceConfigFile = SpaceConfig & {
  $schema?: string;
  space?: string;
  access?: { rules?: unknown[] };
};
