<?php
declare(strict_types=1);

// @generated by `cargo run -p stattic-runtime-compiler --bin protocol-codegen -- --php`.
// Rust protocol and Zero runner constants are the only editable authorities.

const STATTIC_RUNTIME_ZERO_RUNNER_ABI = 'stattic-zero-runner-abi-v2';
const STATTIC_RUNTIME_ZERO_QUICKJS_ABI = 'rquickjs-0.12';
const STATTIC_RUNTIME_ZERO_BUNDLE_MAX_BYTES = 786432;
const STATTIC_RUNTIME_ZERO_BUNDLE_LIMIT = 8;
