[package]
name = "stattic-runtime-compiler"
version = "0.1.0"
edition.workspace = true
publish = false

[dependencies]
payloadwp = { git = "https://github.com/batuhan/payloadwp", rev = "ae340eb52d9ed867ce95d823681ac67a852c908c" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"
stattic-runtime-core = { path = "../stattic-runtime-core" }
stattic-runtime-policy = { path = "../stattic-runtime-policy" }
stattic-zero-runner = { path = "../stattic-zero-runner" }

[[bin]]
name = "stattic-runtime"
path = "src/main.rs"
